// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qlab/v1/service.proto

// Package qlab.v1 — the service surface. Each mutating RPC is one engine event
// (docs/ALGORITHM.md §6): it mutates state, then runs the single reschedule, then
// returns the recomputed schedule. Implemented in Phase 7; stubbed Unimplemented
// for now.

package qlabv1

import (
	_ "github.com/tallam99/qlab/backend/internal/protogen/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListSlotsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResourcePoolId string                 `protobuf:"bytes,1,opt,name=resource_pool_id,json=resourcePoolId,proto3" json:"resource_pool_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListSlotsRequest) Reset() {
	*x = ListSlotsRequest{}
	mi := &file_qlab_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlotsRequest) ProtoMessage() {}

func (x *ListSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlotsRequest.ProtoReflect.Descriptor instead.
func (*ListSlotsRequest) Descriptor() ([]byte, []int) {
	return file_qlab_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListSlotsRequest) GetResourcePoolId() string {
	if x != nil {
		return x.ResourcePoolId
	}
	return ""
}

type ListSlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*Slot                `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSlotsResponse) Reset() {
	*x = ListSlotsResponse{}
	mi := &file_qlab_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlotsResponse) ProtoMessage() {}

func (x *ListSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlotsResponse.ProtoReflect.Descriptor instead.
func (*ListSlotsResponse) Descriptor() ([]byte, []int) {
	return file_qlab_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListSlotsResponse) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

// CreateSlot books a slot. user_id comes from the authenticated caller (Phase 8)
// and slot_priority is assigned by the service, so neither is on the request.
type CreateSlotRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourcePoolId   string                 `protobuf:"bytes,1,opt,name=resource_pool_id,json=resourcePoolId,proto3" json:"resource_pool_id,omitempty"`
	DesiredStart     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=desired_start,json=desiredStart,proto3" json:"desired_start,omitempty"`
	LookaheadMinutes int32                  `protobuf:"varint,3,opt,name=lookahead_minutes,json=lookaheadMinutes,proto3" json:"lookahead_minutes,omitempty"`
	DurationMinutes  int32                  `protobuf:"varint,4,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Note             string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSlotRequest) Reset() {
	*x = CreateSlotRequest{}
	mi := &file_qlab_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSlotRequest) ProtoMessage() {}

func (x *CreateSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSlotRequest.ProtoReflect.Descriptor instead.
func (*CreateSlotRequest) Descriptor() ([]byte, []int) {
	return file_qlab_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSlotRequest) GetResourcePoolId() string {
	if x != nil {
		return x.ResourcePoolId
	}
	return ""
}

func (x *CreateSlotRequest) GetDesiredStart() *timestamppb.Timestamp {
	if x != nil {
		return x.DesiredStart
	}
	return nil
}

func (x *CreateSlotRequest) GetLookaheadMinutes() int32 {
	if x != nil {
		return x.LookaheadMinutes
	}
	return 0
}

func (x *CreateSlotRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *CreateSlotRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type ClockInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClockInRequest) Reset() {
	*x = ClockInRequest{}
	mi := &file_qlab_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClockInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockInRequest) ProtoMessage() {}

func (x *ClockInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockInRequest.ProtoReflect.Descriptor instead.
func (*ClockInRequest) Descriptor() ([]byte, []int) {
	return file_qlab_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ClockInRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

// ClockOut covers clock-out and early-finish (both settle the slot COMPLETE and
// free its resource).
type ClockOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClockOutRequest) Reset() {
	*x = ClockOutRequest{}
	mi := &file_qlab_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClockOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockOutRequest) ProtoMessage() {}

func (x *ClockOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockOutRequest.ProtoReflect.Descriptor instead.
func (*ClockOutRequest) Descriptor() ([]byte, []int) {
	return file_qlab_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ClockOutRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

type CancelSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSlotRequest) Reset() {
	*x = CancelSlotRequest{}
	mi := &file_qlab_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSlotRequest) ProtoMessage() {}

func (x *CancelSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSlotRequest.ProtoReflect.Descriptor instead.
func (*CancelSlotRequest) Descriptor() ([]byte, []int) {
	return file_qlab_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *CancelSlotRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

// PokeOccupant nudges the user holding an overrunning slot to wrap up (the backend
// notifies them). It is the courtesy first step of a resource reclaim, called by
// the next-in-line user — not the backend, which never pokes proactively. It
// changes no schedule state.
type PokeOccupantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokeOccupantRequest) Reset() {
	*x = PokeOccupantRequest{}
	mi := &file_qlab_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokeOccupantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokeOccupantRequest) ProtoMessage() {}

func (x *PokeOccupantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokeOccupantRequest.ProtoReflect.Descriptor instead.
func (*PokeOccupantRequest) Descriptor() ([]byte, []int) {
	return file_qlab_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *PokeOccupantRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

// ForceClockOut boots the user holding an overrunning slot (settles it COMPLETE and
// frees its resource), then reschedules. Called by the next-in-line user as the
// escalation when a poke goes unheeded; the wait and the decision to escalate are
// the users', not the backend's. Authorization (caller is next-in-line for that
// resource, occupant is past their scheduled end) is enforced server-side.
type ForceClockOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceClockOutRequest) Reset() {
	*x = ForceClockOutRequest{}
	mi := &file_qlab_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceClockOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceClockOutRequest) ProtoMessage() {}

func (x *ForceClockOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceClockOutRequest.ProtoReflect.Descriptor instead.
func (*ForceClockOutRequest) Descriptor() ([]byte, []int) {
	return file_qlab_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *ForceClockOutRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

// ForceNoShow reclaims a slot whose clock-in grace lapsed (settles it NO_SHOW and
// frees its place), then reschedules. The sibling of ForceClockOut for the no-show
// case — but with NO prior poke, because the grace period was the implicit warning.
// Called by the next-in-line user; the engine never no-shows anyone automatically.
// Authorization (caller is next-in-line, target is SCHEDULED with grace lapsed) is
// enforced server-side.
type ForceNoShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceNoShowRequest) Reset() {
	*x = ForceNoShowRequest{}
	mi := &file_qlab_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceNoShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceNoShowRequest) ProtoMessage() {}

func (x *ForceNoShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceNoShowRequest.ProtoReflect.Descriptor instead.
func (*ForceNoShowRequest) Descriptor() ([]byte, []int) {
	return file_qlab_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *ForceNoShowRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

// Most mutating RPCs return the recomputed schedule. They carry the same
// RescheduleResult but are distinct types (one response per RPC) so the contract
// can evolve per method without a breaking change rippling across all of them.
type CreateSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *RescheduleResult      `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSlotResponse) Reset() {
	*x = CreateSlotResponse{}
	mi := &file_qlab_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSlotResponse) ProtoMessage() {}

func (x *CreateSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSlotResponse.ProtoReflect.Descriptor instead.
func (*CreateSlotResponse) Descriptor() ([]byte, []int) {
	return file_qlab_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSlotResponse) GetResult() *RescheduleResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ClockInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *RescheduleResult      `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClockInResponse) Reset() {
	*x = ClockInResponse{}
	mi := &file_qlab_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClockInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockInResponse) ProtoMessage() {}

func (x *ClockInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockInResponse.ProtoReflect.Descriptor instead.
func (*ClockInResponse) Descriptor() ([]byte, []int) {
	return file_qlab_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *ClockInResponse) GetResult() *RescheduleResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ClockOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *RescheduleResult      `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClockOutResponse) Reset() {
	*x = ClockOutResponse{}
	mi := &file_qlab_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClockOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockOutResponse) ProtoMessage() {}

func (x *ClockOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockOutResponse.ProtoReflect.Descriptor instead.
func (*ClockOutResponse) Descriptor() ([]byte, []int) {
	return file_qlab_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *ClockOutResponse) GetResult() *RescheduleResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type CancelSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *RescheduleResult      `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSlotResponse) Reset() {
	*x = CancelSlotResponse{}
	mi := &file_qlab_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSlotResponse) ProtoMessage() {}

func (x *CancelSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSlotResponse.ProtoReflect.Descriptor instead.
func (*CancelSlotResponse) Descriptor() ([]byte, []int) {
	return file_qlab_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *CancelSlotResponse) GetResult() *RescheduleResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ForceClockOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *RescheduleResult      `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceClockOutResponse) Reset() {
	*x = ForceClockOutResponse{}
	mi := &file_qlab_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceClockOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceClockOutResponse) ProtoMessage() {}

func (x *ForceClockOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceClockOutResponse.ProtoReflect.Descriptor instead.
func (*ForceClockOutResponse) Descriptor() ([]byte, []int) {
	return file_qlab_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *ForceClockOutResponse) GetResult() *RescheduleResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ForceNoShowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *RescheduleResult      `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceNoShowResponse) Reset() {
	*x = ForceNoShowResponse{}
	mi := &file_qlab_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceNoShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceNoShowResponse) ProtoMessage() {}

func (x *ForceNoShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceNoShowResponse.ProtoReflect.Descriptor instead.
func (*ForceNoShowResponse) Descriptor() ([]byte, []int) {
	return file_qlab_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *ForceNoShowResponse) GetResult() *RescheduleResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// PokeOccupant only sends a nudge, so it changes no schedule state and its response
// is empty.
type PokeOccupantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokeOccupantResponse) Reset() {
	*x = PokeOccupantResponse{}
	mi := &file_qlab_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokeOccupantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokeOccupantResponse) ProtoMessage() {}

func (x *PokeOccupantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokeOccupantResponse.ProtoReflect.Descriptor instead.
func (*PokeOccupantResponse) Descriptor() ([]byte, []int) {
	return file_qlab_v1_service_proto_rawDescGZIP(), []int{15}
}

var File_qlab_v1_service_proto protoreflect.FileDescriptor

const file_qlab_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15qlab/v1/service.proto\x12\aqlab.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13qlab/v1/types.proto\"E\n" +
	"\x10ListSlotsRequest\x121\n" +
	"\x10resource_pool_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eresourcePoolId\"8\n" +
	"\x11ListSlotsResponse\x12#\n" +
	"\x05slots\x18\x01 \x03(\v2\r.qlab.v1.SlotR\x05slots\"\x85\x02\n" +
	"\x11CreateSlotRequest\x121\n" +
	"\x10resource_pool_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eresourcePoolId\x12?\n" +
	"\rdesired_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fdesiredStart\x124\n" +
	"\x11lookahead_minutes\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x10lookaheadMinutes\x122\n" +
	"\x10duration_minutes\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x0fdurationMinutes\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\"2\n" +
	"\x0eClockInRequest\x12 \n" +
	"\aslot_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06slotId\"3\n" +
	"\x0fClockOutRequest\x12 \n" +
	"\aslot_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06slotId\"5\n" +
	"\x11CancelSlotRequest\x12 \n" +
	"\aslot_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06slotId\"7\n" +
	"\x13PokeOccupantRequest\x12 \n" +
	"\aslot_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06slotId\"8\n" +
	"\x14ForceClockOutRequest\x12 \n" +
	"\aslot_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06slotId\"6\n" +
	"\x12ForceNoShowRequest\x12 \n" +
	"\aslot_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06slotId\"G\n" +
	"\x12CreateSlotResponse\x121\n" +
	"\x06result\x18\x01 \x01(\v2\x19.qlab.v1.RescheduleResultR\x06result\"D\n" +
	"\x0fClockInResponse\x121\n" +
	"\x06result\x18\x01 \x01(\v2\x19.qlab.v1.RescheduleResultR\x06result\"E\n" +
	"\x10ClockOutResponse\x121\n" +
	"\x06result\x18\x01 \x01(\v2\x19.qlab.v1.RescheduleResultR\x06result\"G\n" +
	"\x12CancelSlotResponse\x121\n" +
	"\x06result\x18\x01 \x01(\v2\x19.qlab.v1.RescheduleResultR\x06result\"J\n" +
	"\x15ForceClockOutResponse\x121\n" +
	"\x06result\x18\x01 \x01(\v2\x19.qlab.v1.RescheduleResultR\x06result\"H\n" +
	"\x13ForceNoShowResponse\x121\n" +
	"\x06result\x18\x01 \x01(\v2\x19.qlab.v1.RescheduleResultR\x06result\"\x16\n" +
	"\x14PokeOccupantResponse2\xc5\x04\n" +
	"\vQlabService\x12B\n" +
	"\tListSlots\x12\x19.qlab.v1.ListSlotsRequest\x1a\x1a.qlab.v1.ListSlotsResponse\x12E\n" +
	"\n" +
	"CreateSlot\x12\x1a.qlab.v1.CreateSlotRequest\x1a\x1b.qlab.v1.CreateSlotResponse\x12<\n" +
	"\aClockIn\x12\x17.qlab.v1.ClockInRequest\x1a\x18.qlab.v1.ClockInResponse\x12?\n" +
	"\bClockOut\x12\x18.qlab.v1.ClockOutRequest\x1a\x19.qlab.v1.ClockOutResponse\x12E\n" +
	"\n" +
	"CancelSlot\x12\x1a.qlab.v1.CancelSlotRequest\x1a\x1b.qlab.v1.CancelSlotResponse\x12K\n" +
	"\fPokeOccupant\x12\x1c.qlab.v1.PokeOccupantRequest\x1a\x1d.qlab.v1.PokeOccupantResponse\x12N\n" +
	"\rForceClockOut\x12\x1d.qlab.v1.ForceClockOutRequest\x1a\x1e.qlab.v1.ForceClockOutResponse\x12H\n" +
	"\vForceNoShow\x12\x1b.qlab.v1.ForceNoShowRequest\x1a\x1c.qlab.v1.ForceNoShowResponseB\x9b\x01\n" +
	"\vcom.qlab.v1B\fServiceProtoP\x01ZAgithub.com/tallam99/qlab/backend/internal/protogen/qlab/v1;qlabv1\xa2\x02\x03QXX\xaa\x02\aQlab.V1\xca\x02\aQlab\\V1\xe2\x02\x13Qlab\\V1\\GPBMetadata\xea\x02\bQlab::V1b\x06proto3"

var (
	file_qlab_v1_service_proto_rawDescOnce sync.Once
	file_qlab_v1_service_proto_rawDescData []byte
)

func file_qlab_v1_service_proto_rawDescGZIP() []byte {
	file_qlab_v1_service_proto_rawDescOnce.Do(func() {
		file_qlab_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qlab_v1_service_proto_rawDesc), len(file_qlab_v1_service_proto_rawDesc)))
	})
	return file_qlab_v1_service_proto_rawDescData
}

var file_qlab_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_qlab_v1_service_proto_goTypes = []any{
	(*ListSlotsRequest)(nil),      // 0: qlab.v1.ListSlotsRequest
	(*ListSlotsResponse)(nil),     // 1: qlab.v1.ListSlotsResponse
	(*CreateSlotRequest)(nil),     // 2: qlab.v1.CreateSlotRequest
	(*ClockInRequest)(nil),        // 3: qlab.v1.ClockInRequest
	(*ClockOutRequest)(nil),       // 4: qlab.v1.ClockOutRequest
	(*CancelSlotRequest)(nil),     // 5: qlab.v1.CancelSlotRequest
	(*PokeOccupantRequest)(nil),   // 6: qlab.v1.PokeOccupantRequest
	(*ForceClockOutRequest)(nil),  // 7: qlab.v1.ForceClockOutRequest
	(*ForceNoShowRequest)(nil),    // 8: qlab.v1.ForceNoShowRequest
	(*CreateSlotResponse)(nil),    // 9: qlab.v1.CreateSlotResponse
	(*ClockInResponse)(nil),       // 10: qlab.v1.ClockInResponse
	(*ClockOutResponse)(nil),      // 11: qlab.v1.ClockOutResponse
	(*CancelSlotResponse)(nil),    // 12: qlab.v1.CancelSlotResponse
	(*ForceClockOutResponse)(nil), // 13: qlab.v1.ForceClockOutResponse
	(*ForceNoShowResponse)(nil),   // 14: qlab.v1.ForceNoShowResponse
	(*PokeOccupantResponse)(nil),  // 15: qlab.v1.PokeOccupantResponse
	(*Slot)(nil),                  // 16: qlab.v1.Slot
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
	(*RescheduleResult)(nil),      // 18: qlab.v1.RescheduleResult
}
var file_qlab_v1_service_proto_depIdxs = []int32{
	16, // 0: qlab.v1.ListSlotsResponse.slots:type_name -> qlab.v1.Slot
	17, // 1: qlab.v1.CreateSlotRequest.desired_start:type_name -> google.protobuf.Timestamp
	18, // 2: qlab.v1.CreateSlotResponse.result:type_name -> qlab.v1.RescheduleResult
	18, // 3: qlab.v1.ClockInResponse.result:type_name -> qlab.v1.RescheduleResult
	18, // 4: qlab.v1.ClockOutResponse.result:type_name -> qlab.v1.RescheduleResult
	18, // 5: qlab.v1.CancelSlotResponse.result:type_name -> qlab.v1.RescheduleResult
	18, // 6: qlab.v1.ForceClockOutResponse.result:type_name -> qlab.v1.RescheduleResult
	18, // 7: qlab.v1.ForceNoShowResponse.result:type_name -> qlab.v1.RescheduleResult
	0,  // 8: qlab.v1.QlabService.ListSlots:input_type -> qlab.v1.ListSlotsRequest
	2,  // 9: qlab.v1.QlabService.CreateSlot:input_type -> qlab.v1.CreateSlotRequest
	3,  // 10: qlab.v1.QlabService.ClockIn:input_type -> qlab.v1.ClockInRequest
	4,  // 11: qlab.v1.QlabService.ClockOut:input_type -> qlab.v1.ClockOutRequest
	5,  // 12: qlab.v1.QlabService.CancelSlot:input_type -> qlab.v1.CancelSlotRequest
	6,  // 13: qlab.v1.QlabService.PokeOccupant:input_type -> qlab.v1.PokeOccupantRequest
	7,  // 14: qlab.v1.QlabService.ForceClockOut:input_type -> qlab.v1.ForceClockOutRequest
	8,  // 15: qlab.v1.QlabService.ForceNoShow:input_type -> qlab.v1.ForceNoShowRequest
	1,  // 16: qlab.v1.QlabService.ListSlots:output_type -> qlab.v1.ListSlotsResponse
	9,  // 17: qlab.v1.QlabService.CreateSlot:output_type -> qlab.v1.CreateSlotResponse
	10, // 18: qlab.v1.QlabService.ClockIn:output_type -> qlab.v1.ClockInResponse
	11, // 19: qlab.v1.QlabService.ClockOut:output_type -> qlab.v1.ClockOutResponse
	12, // 20: qlab.v1.QlabService.CancelSlot:output_type -> qlab.v1.CancelSlotResponse
	15, // 21: qlab.v1.QlabService.PokeOccupant:output_type -> qlab.v1.PokeOccupantResponse
	13, // 22: qlab.v1.QlabService.ForceClockOut:output_type -> qlab.v1.ForceClockOutResponse
	14, // 23: qlab.v1.QlabService.ForceNoShow:output_type -> qlab.v1.ForceNoShowResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_qlab_v1_service_proto_init() }
func file_qlab_v1_service_proto_init() {
	if File_qlab_v1_service_proto != nil {
		return
	}
	file_qlab_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qlab_v1_service_proto_rawDesc), len(file_qlab_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qlab_v1_service_proto_goTypes,
		DependencyIndexes: file_qlab_v1_service_proto_depIdxs,
		MessageInfos:      file_qlab_v1_service_proto_msgTypes,
	}.Build()
	File_qlab_v1_service_proto = out.File
	file_qlab_v1_service_proto_goTypes = nil
	file_qlab_v1_service_proto_depIdxs = nil
}
