// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: qlab/v1/service.proto

// Package qlab.v1 — the service surface. Each mutating RPC is one engine event
// (docs/ALGORITHM.md §6): it mutates state, then runs the single reschedule, then
// returns the recomputed schedule. Implemented in Phase 7; stubbed Unimplemented
// for now.
package qlabv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/tallam99/qlab/backend/internal/protogen/qlab/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// QlabServiceName is the fully-qualified name of the QlabService service.
	QlabServiceName = "qlab.v1.QlabService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// QlabServiceListSlotsProcedure is the fully-qualified name of the QlabService's ListSlots RPC.
	QlabServiceListSlotsProcedure = "/qlab.v1.QlabService/ListSlots"
	// QlabServiceCreateSlotProcedure is the fully-qualified name of the QlabService's CreateSlot RPC.
	QlabServiceCreateSlotProcedure = "/qlab.v1.QlabService/CreateSlot"
	// QlabServiceClockInProcedure is the fully-qualified name of the QlabService's ClockIn RPC.
	QlabServiceClockInProcedure = "/qlab.v1.QlabService/ClockIn"
	// QlabServiceClockOutProcedure is the fully-qualified name of the QlabService's ClockOut RPC.
	QlabServiceClockOutProcedure = "/qlab.v1.QlabService/ClockOut"
	// QlabServiceCancelSlotProcedure is the fully-qualified name of the QlabService's CancelSlot RPC.
	QlabServiceCancelSlotProcedure = "/qlab.v1.QlabService/CancelSlot"
	// QlabServicePokeOccupantProcedure is the fully-qualified name of the QlabService's PokeOccupant
	// RPC.
	QlabServicePokeOccupantProcedure = "/qlab.v1.QlabService/PokeOccupant"
	// QlabServiceForceClockOutProcedure is the fully-qualified name of the QlabService's ForceClockOut
	// RPC.
	QlabServiceForceClockOutProcedure = "/qlab.v1.QlabService/ForceClockOut"
	// QlabServiceForceNoShowProcedure is the fully-qualified name of the QlabService's ForceNoShow RPC.
	QlabServiceForceNoShowProcedure = "/qlab.v1.QlabService/ForceNoShow"
)

// QlabServiceClient is a client for the qlab.v1.QlabService service.
type QlabServiceClient interface {
	ListSlots(context.Context, *connect.Request[v1.ListSlotsRequest]) (*connect.Response[v1.ListSlotsResponse], error)
	CreateSlot(context.Context, *connect.Request[v1.CreateSlotRequest]) (*connect.Response[v1.CreateSlotResponse], error)
	ClockIn(context.Context, *connect.Request[v1.ClockInRequest]) (*connect.Response[v1.ClockInResponse], error)
	ClockOut(context.Context, *connect.Request[v1.ClockOutRequest]) (*connect.Response[v1.ClockOutResponse], error)
	CancelSlot(context.Context, *connect.Request[v1.CancelSlotRequest]) (*connect.Response[v1.CancelSlotResponse], error)
	PokeOccupant(context.Context, *connect.Request[v1.PokeOccupantRequest]) (*connect.Response[v1.PokeOccupantResponse], error)
	ForceClockOut(context.Context, *connect.Request[v1.ForceClockOutRequest]) (*connect.Response[v1.ForceClockOutResponse], error)
	ForceNoShow(context.Context, *connect.Request[v1.ForceNoShowRequest]) (*connect.Response[v1.ForceNoShowResponse], error)
}

// NewQlabServiceClient constructs a client for the qlab.v1.QlabService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewQlabServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) QlabServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	qlabServiceMethods := v1.File_qlab_v1_service_proto.Services().ByName("QlabService").Methods()
	return &qlabServiceClient{
		listSlots: connect.NewClient[v1.ListSlotsRequest, v1.ListSlotsResponse](
			httpClient,
			baseURL+QlabServiceListSlotsProcedure,
			connect.WithSchema(qlabServiceMethods.ByName("ListSlots")),
			connect.WithClientOptions(opts...),
		),
		createSlot: connect.NewClient[v1.CreateSlotRequest, v1.CreateSlotResponse](
			httpClient,
			baseURL+QlabServiceCreateSlotProcedure,
			connect.WithSchema(qlabServiceMethods.ByName("CreateSlot")),
			connect.WithClientOptions(opts...),
		),
		clockIn: connect.NewClient[v1.ClockInRequest, v1.ClockInResponse](
			httpClient,
			baseURL+QlabServiceClockInProcedure,
			connect.WithSchema(qlabServiceMethods.ByName("ClockIn")),
			connect.WithClientOptions(opts...),
		),
		clockOut: connect.NewClient[v1.ClockOutRequest, v1.ClockOutResponse](
			httpClient,
			baseURL+QlabServiceClockOutProcedure,
			connect.WithSchema(qlabServiceMethods.ByName("ClockOut")),
			connect.WithClientOptions(opts...),
		),
		cancelSlot: connect.NewClient[v1.CancelSlotRequest, v1.CancelSlotResponse](
			httpClient,
			baseURL+QlabServiceCancelSlotProcedure,
			connect.WithSchema(qlabServiceMethods.ByName("CancelSlot")),
			connect.WithClientOptions(opts...),
		),
		pokeOccupant: connect.NewClient[v1.PokeOccupantRequest, v1.PokeOccupantResponse](
			httpClient,
			baseURL+QlabServicePokeOccupantProcedure,
			connect.WithSchema(qlabServiceMethods.ByName("PokeOccupant")),
			connect.WithClientOptions(opts...),
		),
		forceClockOut: connect.NewClient[v1.ForceClockOutRequest, v1.ForceClockOutResponse](
			httpClient,
			baseURL+QlabServiceForceClockOutProcedure,
			connect.WithSchema(qlabServiceMethods.ByName("ForceClockOut")),
			connect.WithClientOptions(opts...),
		),
		forceNoShow: connect.NewClient[v1.ForceNoShowRequest, v1.ForceNoShowResponse](
			httpClient,
			baseURL+QlabServiceForceNoShowProcedure,
			connect.WithSchema(qlabServiceMethods.ByName("ForceNoShow")),
			connect.WithClientOptions(opts...),
		),
	}
}

// qlabServiceClient implements QlabServiceClient.
type qlabServiceClient struct {
	listSlots     *connect.Client[v1.ListSlotsRequest, v1.ListSlotsResponse]
	createSlot    *connect.Client[v1.CreateSlotRequest, v1.CreateSlotResponse]
	clockIn       *connect.Client[v1.ClockInRequest, v1.ClockInResponse]
	clockOut      *connect.Client[v1.ClockOutRequest, v1.ClockOutResponse]
	cancelSlot    *connect.Client[v1.CancelSlotRequest, v1.CancelSlotResponse]
	pokeOccupant  *connect.Client[v1.PokeOccupantRequest, v1.PokeOccupantResponse]
	forceClockOut *connect.Client[v1.ForceClockOutRequest, v1.ForceClockOutResponse]
	forceNoShow   *connect.Client[v1.ForceNoShowRequest, v1.ForceNoShowResponse]
}

// ListSlots calls qlab.v1.QlabService.ListSlots.
func (c *qlabServiceClient) ListSlots(ctx context.Context, req *connect.Request[v1.ListSlotsRequest]) (*connect.Response[v1.ListSlotsResponse], error) {
	return c.listSlots.CallUnary(ctx, req)
}

// CreateSlot calls qlab.v1.QlabService.CreateSlot.
func (c *qlabServiceClient) CreateSlot(ctx context.Context, req *connect.Request[v1.CreateSlotRequest]) (*connect.Response[v1.CreateSlotResponse], error) {
	return c.createSlot.CallUnary(ctx, req)
}

// ClockIn calls qlab.v1.QlabService.ClockIn.
func (c *qlabServiceClient) ClockIn(ctx context.Context, req *connect.Request[v1.ClockInRequest]) (*connect.Response[v1.ClockInResponse], error) {
	return c.clockIn.CallUnary(ctx, req)
}

// ClockOut calls qlab.v1.QlabService.ClockOut.
func (c *qlabServiceClient) ClockOut(ctx context.Context, req *connect.Request[v1.ClockOutRequest]) (*connect.Response[v1.ClockOutResponse], error) {
	return c.clockOut.CallUnary(ctx, req)
}

// CancelSlot calls qlab.v1.QlabService.CancelSlot.
func (c *qlabServiceClient) CancelSlot(ctx context.Context, req *connect.Request[v1.CancelSlotRequest]) (*connect.Response[v1.CancelSlotResponse], error) {
	return c.cancelSlot.CallUnary(ctx, req)
}

// PokeOccupant calls qlab.v1.QlabService.PokeOccupant.
func (c *qlabServiceClient) PokeOccupant(ctx context.Context, req *connect.Request[v1.PokeOccupantRequest]) (*connect.Response[v1.PokeOccupantResponse], error) {
	return c.pokeOccupant.CallUnary(ctx, req)
}

// ForceClockOut calls qlab.v1.QlabService.ForceClockOut.
func (c *qlabServiceClient) ForceClockOut(ctx context.Context, req *connect.Request[v1.ForceClockOutRequest]) (*connect.Response[v1.ForceClockOutResponse], error) {
	return c.forceClockOut.CallUnary(ctx, req)
}

// ForceNoShow calls qlab.v1.QlabService.ForceNoShow.
func (c *qlabServiceClient) ForceNoShow(ctx context.Context, req *connect.Request[v1.ForceNoShowRequest]) (*connect.Response[v1.ForceNoShowResponse], error) {
	return c.forceNoShow.CallUnary(ctx, req)
}

// QlabServiceHandler is an implementation of the qlab.v1.QlabService service.
type QlabServiceHandler interface {
	ListSlots(context.Context, *connect.Request[v1.ListSlotsRequest]) (*connect.Response[v1.ListSlotsResponse], error)
	CreateSlot(context.Context, *connect.Request[v1.CreateSlotRequest]) (*connect.Response[v1.CreateSlotResponse], error)
	ClockIn(context.Context, *connect.Request[v1.ClockInRequest]) (*connect.Response[v1.ClockInResponse], error)
	ClockOut(context.Context, *connect.Request[v1.ClockOutRequest]) (*connect.Response[v1.ClockOutResponse], error)
	CancelSlot(context.Context, *connect.Request[v1.CancelSlotRequest]) (*connect.Response[v1.CancelSlotResponse], error)
	PokeOccupant(context.Context, *connect.Request[v1.PokeOccupantRequest]) (*connect.Response[v1.PokeOccupantResponse], error)
	ForceClockOut(context.Context, *connect.Request[v1.ForceClockOutRequest]) (*connect.Response[v1.ForceClockOutResponse], error)
	ForceNoShow(context.Context, *connect.Request[v1.ForceNoShowRequest]) (*connect.Response[v1.ForceNoShowResponse], error)
}

// NewQlabServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewQlabServiceHandler(svc QlabServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	qlabServiceMethods := v1.File_qlab_v1_service_proto.Services().ByName("QlabService").Methods()
	qlabServiceListSlotsHandler := connect.NewUnaryHandler(
		QlabServiceListSlotsProcedure,
		svc.ListSlots,
		connect.WithSchema(qlabServiceMethods.ByName("ListSlots")),
		connect.WithHandlerOptions(opts...),
	)
	qlabServiceCreateSlotHandler := connect.NewUnaryHandler(
		QlabServiceCreateSlotProcedure,
		svc.CreateSlot,
		connect.WithSchema(qlabServiceMethods.ByName("CreateSlot")),
		connect.WithHandlerOptions(opts...),
	)
	qlabServiceClockInHandler := connect.NewUnaryHandler(
		QlabServiceClockInProcedure,
		svc.ClockIn,
		connect.WithSchema(qlabServiceMethods.ByName("ClockIn")),
		connect.WithHandlerOptions(opts...),
	)
	qlabServiceClockOutHandler := connect.NewUnaryHandler(
		QlabServiceClockOutProcedure,
		svc.ClockOut,
		connect.WithSchema(qlabServiceMethods.ByName("ClockOut")),
		connect.WithHandlerOptions(opts...),
	)
	qlabServiceCancelSlotHandler := connect.NewUnaryHandler(
		QlabServiceCancelSlotProcedure,
		svc.CancelSlot,
		connect.WithSchema(qlabServiceMethods.ByName("CancelSlot")),
		connect.WithHandlerOptions(opts...),
	)
	qlabServicePokeOccupantHandler := connect.NewUnaryHandler(
		QlabServicePokeOccupantProcedure,
		svc.PokeOccupant,
		connect.WithSchema(qlabServiceMethods.ByName("PokeOccupant")),
		connect.WithHandlerOptions(opts...),
	)
	qlabServiceForceClockOutHandler := connect.NewUnaryHandler(
		QlabServiceForceClockOutProcedure,
		svc.ForceClockOut,
		connect.WithSchema(qlabServiceMethods.ByName("ForceClockOut")),
		connect.WithHandlerOptions(opts...),
	)
	qlabServiceForceNoShowHandler := connect.NewUnaryHandler(
		QlabServiceForceNoShowProcedure,
		svc.ForceNoShow,
		connect.WithSchema(qlabServiceMethods.ByName("ForceNoShow")),
		connect.WithHandlerOptions(opts...),
	)
	return "/qlab.v1.QlabService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case QlabServiceListSlotsProcedure:
			qlabServiceListSlotsHandler.ServeHTTP(w, r)
		case QlabServiceCreateSlotProcedure:
			qlabServiceCreateSlotHandler.ServeHTTP(w, r)
		case QlabServiceClockInProcedure:
			qlabServiceClockInHandler.ServeHTTP(w, r)
		case QlabServiceClockOutProcedure:
			qlabServiceClockOutHandler.ServeHTTP(w, r)
		case QlabServiceCancelSlotProcedure:
			qlabServiceCancelSlotHandler.ServeHTTP(w, r)
		case QlabServicePokeOccupantProcedure:
			qlabServicePokeOccupantHandler.ServeHTTP(w, r)
		case QlabServiceForceClockOutProcedure:
			qlabServiceForceClockOutHandler.ServeHTTP(w, r)
		case QlabServiceForceNoShowProcedure:
			qlabServiceForceNoShowHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedQlabServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedQlabServiceHandler struct{}

func (UnimplementedQlabServiceHandler) ListSlots(context.Context, *connect.Request[v1.ListSlotsRequest]) (*connect.Response[v1.ListSlotsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("qlab.v1.QlabService.ListSlots is not implemented"))
}

func (UnimplementedQlabServiceHandler) CreateSlot(context.Context, *connect.Request[v1.CreateSlotRequest]) (*connect.Response[v1.CreateSlotResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("qlab.v1.QlabService.CreateSlot is not implemented"))
}

func (UnimplementedQlabServiceHandler) ClockIn(context.Context, *connect.Request[v1.ClockInRequest]) (*connect.Response[v1.ClockInResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("qlab.v1.QlabService.ClockIn is not implemented"))
}

func (UnimplementedQlabServiceHandler) ClockOut(context.Context, *connect.Request[v1.ClockOutRequest]) (*connect.Response[v1.ClockOutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("qlab.v1.QlabService.ClockOut is not implemented"))
}

func (UnimplementedQlabServiceHandler) CancelSlot(context.Context, *connect.Request[v1.CancelSlotRequest]) (*connect.Response[v1.CancelSlotResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("qlab.v1.QlabService.CancelSlot is not implemented"))
}

func (UnimplementedQlabServiceHandler) PokeOccupant(context.Context, *connect.Request[v1.PokeOccupantRequest]) (*connect.Response[v1.PokeOccupantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("qlab.v1.QlabService.PokeOccupant is not implemented"))
}

func (UnimplementedQlabServiceHandler) ForceClockOut(context.Context, *connect.Request[v1.ForceClockOutRequest]) (*connect.Response[v1.ForceClockOutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("qlab.v1.QlabService.ForceClockOut is not implemented"))
}

func (UnimplementedQlabServiceHandler) ForceNoShow(context.Context, *connect.Request[v1.ForceNoShowRequest]) (*connect.Response[v1.ForceNoShowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("qlab.v1.QlabService.ForceNoShow is not implemented"))
}
