// Code generated by "enumer -type=LabRole -trimprefix=LabRole -transform=upper -output=labrole_enumer.go"; DO NOT EDIT.

package store

import (
	"fmt"
	"strings"
)

const _LabRoleName = "UNKNOWNHEADMEMBER"

var _LabRoleIndex = [...]uint8{0, 7, 11, 17}

const _LabRoleLowerName = "unknownheadmember"

func (i LabRole) String() string {
	if i < 0 || i >= LabRole(len(_LabRoleIndex)-1) {
		return fmt.Sprintf("LabRole(%d)", i)
	}
	return _LabRoleName[_LabRoleIndex[i]:_LabRoleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LabRoleNoOp() {
	var x [1]struct{}
	_ = x[LabRoleUnknown-(0)]
	_ = x[LabRoleHead-(1)]
	_ = x[LabRoleMember-(2)]
}

var _LabRoleValues = []LabRole{LabRoleUnknown, LabRoleHead, LabRoleMember}

var _LabRoleNameToValueMap = map[string]LabRole{
	_LabRoleName[0:7]:        LabRoleUnknown,
	_LabRoleLowerName[0:7]:   LabRoleUnknown,
	_LabRoleName[7:11]:       LabRoleHead,
	_LabRoleLowerName[7:11]:  LabRoleHead,
	_LabRoleName[11:17]:      LabRoleMember,
	_LabRoleLowerName[11:17]: LabRoleMember,
}

var _LabRoleNames = []string{
	_LabRoleName[0:7],
	_LabRoleName[7:11],
	_LabRoleName[11:17],
}

// LabRoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LabRoleString(s string) (LabRole, error) {
	if val, ok := _LabRoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LabRoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LabRole values", s)
}

// LabRoleValues returns all values of the enum
func LabRoleValues() []LabRole {
	return _LabRoleValues
}

// LabRoleStrings returns a slice of all String values of the enum
func LabRoleStrings() []string {
	strs := make([]string, len(_LabRoleNames))
	copy(strs, _LabRoleNames)
	return strs
}

// IsALabRole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i LabRole) IsALabRole() bool {
	for _, v := range _LabRoleValues {
		if i == v {
			return true
		}
	}
	return false
}
