// Code generated by "enumer -type=ResourceKind -trimprefix=ResourceKind -transform=snake-upper -output=resourcekind_enumer.go"; DO NOT EDIT.

package store

import (
	"fmt"
	"strings"
)

const _ResourceKindName = "UNKNOWNVENT_HOOD"

var _ResourceKindIndex = [...]uint8{0, 7, 16}

const _ResourceKindLowerName = "unknownvent_hood"

func (i ResourceKind) String() string {
	if i < 0 || i >= ResourceKind(len(_ResourceKindIndex)-1) {
		return fmt.Sprintf("ResourceKind(%d)", i)
	}
	return _ResourceKindName[_ResourceKindIndex[i]:_ResourceKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ResourceKindNoOp() {
	var x [1]struct{}
	_ = x[ResourceKindUnknown-(0)]
	_ = x[ResourceKindVentHood-(1)]
}

var _ResourceKindValues = []ResourceKind{ResourceKindUnknown, ResourceKindVentHood}

var _ResourceKindNameToValueMap = map[string]ResourceKind{
	_ResourceKindName[0:7]:       ResourceKindUnknown,
	_ResourceKindLowerName[0:7]:  ResourceKindUnknown,
	_ResourceKindName[7:16]:      ResourceKindVentHood,
	_ResourceKindLowerName[7:16]: ResourceKindVentHood,
}

var _ResourceKindNames = []string{
	_ResourceKindName[0:7],
	_ResourceKindName[7:16],
}

// ResourceKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ResourceKindString(s string) (ResourceKind, error) {
	if val, ok := _ResourceKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ResourceKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ResourceKind values", s)
}

// ResourceKindValues returns all values of the enum
func ResourceKindValues() []ResourceKind {
	return _ResourceKindValues
}

// ResourceKindStrings returns a slice of all String values of the enum
func ResourceKindStrings() []string {
	strs := make([]string, len(_ResourceKindNames))
	copy(strs, _ResourceKindNames)
	return strs
}

// IsAResourceKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ResourceKind) IsAResourceKind() bool {
	for _, v := range _ResourceKindValues {
		if i == v {
			return true
		}
	}
	return false
}
