// Code generated by mockery. DO NOT EDIT.

package storemock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// CountLabs provides a mock function with given fields: ctx
func (_m *MockStore) CountLabs(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountLabs")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_CountLabs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountLabs'
type MockStore_CountLabs_Call struct {
	*mock.Call
}

// CountLabs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) CountLabs(ctx interface{}) *MockStore_CountLabs_Call {
	return &MockStore_CountLabs_Call{Call: _e.mock.On("CountLabs", ctx)}
}

func (_c *MockStore_CountLabs_Call) Run(run func(ctx context.Context)) *MockStore_CountLabs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_CountLabs_Call) Return(_a0 int, _a1 error) *MockStore_CountLabs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_CountLabs_Call) RunAndReturn(run func(context.Context) (int, error)) *MockStore_CountLabs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
