// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: qlab/dev/v1/dev.proto

// Package qlab.dev.v1 is the STAGING/LOCAL-ONLY operator surface: provision demo
// lab workspaces, mint a token to act as any seeded user, and inspect/tear down
// workspaces. It is the dev-experience tooling (decision 0008), deliberately a
// SEPARATE service from qlab.v1 so the production binary simply never mounts it —
// there is no operator capability in prod by construction. Every call is gated by
// the operator secret; the server refuses to enable any of this in production.
package devv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/tallam99/qlab/backend/internal/protogen/qlab/dev/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DevServiceName is the fully-qualified name of the DevService service.
	DevServiceName = "qlab.dev.v1.DevService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DevServiceProvisionLabProcedure is the fully-qualified name of the DevService's ProvisionLab RPC.
	DevServiceProvisionLabProcedure = "/qlab.dev.v1.DevService/ProvisionLab"
	// DevServiceMintTokenProcedure is the fully-qualified name of the DevService's MintToken RPC.
	DevServiceMintTokenProcedure = "/qlab.dev.v1.DevService/MintToken"
	// DevServiceListLabsProcedure is the fully-qualified name of the DevService's ListLabs RPC.
	DevServiceListLabsProcedure = "/qlab.dev.v1.DevService/ListLabs"
	// DevServiceGetLabProcedure is the fully-qualified name of the DevService's GetLab RPC.
	DevServiceGetLabProcedure = "/qlab.dev.v1.DevService/GetLab"
	// DevServiceTeardownLabProcedure is the fully-qualified name of the DevService's TeardownLab RPC.
	DevServiceTeardownLabProcedure = "/qlab.dev.v1.DevService/TeardownLab"
)

// DevServiceClient is a client for the qlab.dev.v1.DevService service.
type DevServiceClient interface {
	ProvisionLab(context.Context, *connect.Request[v1.ProvisionLabRequest]) (*connect.Response[v1.ProvisionLabResponse], error)
	MintToken(context.Context, *connect.Request[v1.MintTokenRequest]) (*connect.Response[v1.MintTokenResponse], error)
	ListLabs(context.Context, *connect.Request[v1.ListLabsRequest]) (*connect.Response[v1.ListLabsResponse], error)
	GetLab(context.Context, *connect.Request[v1.GetLabRequest]) (*connect.Response[v1.GetLabResponse], error)
	TeardownLab(context.Context, *connect.Request[v1.TeardownLabRequest]) (*connect.Response[v1.TeardownLabResponse], error)
}

// NewDevServiceClient constructs a client for the qlab.dev.v1.DevService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDevServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DevServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	devServiceMethods := v1.File_qlab_dev_v1_dev_proto.Services().ByName("DevService").Methods()
	return &devServiceClient{
		provisionLab: connect.NewClient[v1.ProvisionLabRequest, v1.ProvisionLabResponse](
			httpClient,
			baseURL+DevServiceProvisionLabProcedure,
			connect.WithSchema(devServiceMethods.ByName("ProvisionLab")),
			connect.WithClientOptions(opts...),
		),
		mintToken: connect.NewClient[v1.MintTokenRequest, v1.MintTokenResponse](
			httpClient,
			baseURL+DevServiceMintTokenProcedure,
			connect.WithSchema(devServiceMethods.ByName("MintToken")),
			connect.WithClientOptions(opts...),
		),
		listLabs: connect.NewClient[v1.ListLabsRequest, v1.ListLabsResponse](
			httpClient,
			baseURL+DevServiceListLabsProcedure,
			connect.WithSchema(devServiceMethods.ByName("ListLabs")),
			connect.WithClientOptions(opts...),
		),
		getLab: connect.NewClient[v1.GetLabRequest, v1.GetLabResponse](
			httpClient,
			baseURL+DevServiceGetLabProcedure,
			connect.WithSchema(devServiceMethods.ByName("GetLab")),
			connect.WithClientOptions(opts...),
		),
		teardownLab: connect.NewClient[v1.TeardownLabRequest, v1.TeardownLabResponse](
			httpClient,
			baseURL+DevServiceTeardownLabProcedure,
			connect.WithSchema(devServiceMethods.ByName("TeardownLab")),
			connect.WithClientOptions(opts...),
		),
	}
}

// devServiceClient implements DevServiceClient.
type devServiceClient struct {
	provisionLab *connect.Client[v1.ProvisionLabRequest, v1.ProvisionLabResponse]
	mintToken    *connect.Client[v1.MintTokenRequest, v1.MintTokenResponse]
	listLabs     *connect.Client[v1.ListLabsRequest, v1.ListLabsResponse]
	getLab       *connect.Client[v1.GetLabRequest, v1.GetLabResponse]
	teardownLab  *connect.Client[v1.TeardownLabRequest, v1.TeardownLabResponse]
}

// ProvisionLab calls qlab.dev.v1.DevService.ProvisionLab.
func (c *devServiceClient) ProvisionLab(ctx context.Context, req *connect.Request[v1.ProvisionLabRequest]) (*connect.Response[v1.ProvisionLabResponse], error) {
	return c.provisionLab.CallUnary(ctx, req)
}

// MintToken calls qlab.dev.v1.DevService.MintToken.
func (c *devServiceClient) MintToken(ctx context.Context, req *connect.Request[v1.MintTokenRequest]) (*connect.Response[v1.MintTokenResponse], error) {
	return c.mintToken.CallUnary(ctx, req)
}

// ListLabs calls qlab.dev.v1.DevService.ListLabs.
func (c *devServiceClient) ListLabs(ctx context.Context, req *connect.Request[v1.ListLabsRequest]) (*connect.Response[v1.ListLabsResponse], error) {
	return c.listLabs.CallUnary(ctx, req)
}

// GetLab calls qlab.dev.v1.DevService.GetLab.
func (c *devServiceClient) GetLab(ctx context.Context, req *connect.Request[v1.GetLabRequest]) (*connect.Response[v1.GetLabResponse], error) {
	return c.getLab.CallUnary(ctx, req)
}

// TeardownLab calls qlab.dev.v1.DevService.TeardownLab.
func (c *devServiceClient) TeardownLab(ctx context.Context, req *connect.Request[v1.TeardownLabRequest]) (*connect.Response[v1.TeardownLabResponse], error) {
	return c.teardownLab.CallUnary(ctx, req)
}

// DevServiceHandler is an implementation of the qlab.dev.v1.DevService service.
type DevServiceHandler interface {
	ProvisionLab(context.Context, *connect.Request[v1.ProvisionLabRequest]) (*connect.Response[v1.ProvisionLabResponse], error)
	MintToken(context.Context, *connect.Request[v1.MintTokenRequest]) (*connect.Response[v1.MintTokenResponse], error)
	ListLabs(context.Context, *connect.Request[v1.ListLabsRequest]) (*connect.Response[v1.ListLabsResponse], error)
	GetLab(context.Context, *connect.Request[v1.GetLabRequest]) (*connect.Response[v1.GetLabResponse], error)
	TeardownLab(context.Context, *connect.Request[v1.TeardownLabRequest]) (*connect.Response[v1.TeardownLabResponse], error)
}

// NewDevServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDevServiceHandler(svc DevServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	devServiceMethods := v1.File_qlab_dev_v1_dev_proto.Services().ByName("DevService").Methods()
	devServiceProvisionLabHandler := connect.NewUnaryHandler(
		DevServiceProvisionLabProcedure,
		svc.ProvisionLab,
		connect.WithSchema(devServiceMethods.ByName("ProvisionLab")),
		connect.WithHandlerOptions(opts...),
	)
	devServiceMintTokenHandler := connect.NewUnaryHandler(
		DevServiceMintTokenProcedure,
		svc.MintToken,
		connect.WithSchema(devServiceMethods.ByName("MintToken")),
		connect.WithHandlerOptions(opts...),
	)
	devServiceListLabsHandler := connect.NewUnaryHandler(
		DevServiceListLabsProcedure,
		svc.ListLabs,
		connect.WithSchema(devServiceMethods.ByName("ListLabs")),
		connect.WithHandlerOptions(opts...),
	)
	devServiceGetLabHandler := connect.NewUnaryHandler(
		DevServiceGetLabProcedure,
		svc.GetLab,
		connect.WithSchema(devServiceMethods.ByName("GetLab")),
		connect.WithHandlerOptions(opts...),
	)
	devServiceTeardownLabHandler := connect.NewUnaryHandler(
		DevServiceTeardownLabProcedure,
		svc.TeardownLab,
		connect.WithSchema(devServiceMethods.ByName("TeardownLab")),
		connect.WithHandlerOptions(opts...),
	)
	return "/qlab.dev.v1.DevService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DevServiceProvisionLabProcedure:
			devServiceProvisionLabHandler.ServeHTTP(w, r)
		case DevServiceMintTokenProcedure:
			devServiceMintTokenHandler.ServeHTTP(w, r)
		case DevServiceListLabsProcedure:
			devServiceListLabsHandler.ServeHTTP(w, r)
		case DevServiceGetLabProcedure:
			devServiceGetLabHandler.ServeHTTP(w, r)
		case DevServiceTeardownLabProcedure:
			devServiceTeardownLabHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDevServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDevServiceHandler struct{}

func (UnimplementedDevServiceHandler) ProvisionLab(context.Context, *connect.Request[v1.ProvisionLabRequest]) (*connect.Response[v1.ProvisionLabResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("qlab.dev.v1.DevService.ProvisionLab is not implemented"))
}

func (UnimplementedDevServiceHandler) MintToken(context.Context, *connect.Request[v1.MintTokenRequest]) (*connect.Response[v1.MintTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("qlab.dev.v1.DevService.MintToken is not implemented"))
}

func (UnimplementedDevServiceHandler) ListLabs(context.Context, *connect.Request[v1.ListLabsRequest]) (*connect.Response[v1.ListLabsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("qlab.dev.v1.DevService.ListLabs is not implemented"))
}

func (UnimplementedDevServiceHandler) GetLab(context.Context, *connect.Request[v1.GetLabRequest]) (*connect.Response[v1.GetLabResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("qlab.dev.v1.DevService.GetLab is not implemented"))
}

func (UnimplementedDevServiceHandler) TeardownLab(context.Context, *connect.Request[v1.TeardownLabRequest]) (*connect.Response[v1.TeardownLabResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("qlab.dev.v1.DevService.TeardownLab is not implemented"))
}
