// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qlab/dev/v1/dev.proto

// Package qlab.dev.v1 is the STAGING/LOCAL-ONLY operator surface: provision demo
// lab workspaces, mint a token to act as any seeded user, and inspect/tear down
// workspaces. It is the dev-experience tooling (decision 0008), deliberately a
// SEPARATE service from qlab.v1 so the production binary simply never mounts it —
// there is no operator capability in prod by construction. Every call is gated by
// the operator secret; the server refuses to enable any of this in production.

package devv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/tallam99/qlab/backend/internal/protogen/qlab/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LabMember pairs a provisioned user with their role in the workspace.
type LabMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *v1.User               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Role          v1.LabRole             `protobuf:"varint,2,opt,name=role,proto3,enum=qlab.v1.LabRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabMember) Reset() {
	*x = LabMember{}
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabMember) ProtoMessage() {}

func (x *LabMember) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabMember.ProtoReflect.Descriptor instead.
func (*LabMember) Descriptor() ([]byte, []int) {
	return file_qlab_dev_v1_dev_proto_rawDescGZIP(), []int{0}
}

func (x *LabMember) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LabMember) GetRole() v1.LabRole {
	if x != nil {
		return x.Role
	}
	return v1.LabRole(0)
}

// ProvisionLab creates a fresh demo workspace: a lab (named for the feature), a
// head plus member_count members, and one resource pool with resource_count
// interchangeable resources. Users are created unlinked (no Firebase identity yet);
// MintToken / first login links them.
type ProvisionLabRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// feature labels the workspace (stored as the lab name) so workspaces can be
	// listed/torn down per feature.
	Feature string `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	// member_count is how many MEMBER users to create in addition to the single HEAD.
	MemberCount int32 `protobuf:"varint,2,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	// resource_count is how many interchangeable resources the pool holds.
	ResourceCount int32 `protobuf:"varint,3,opt,name=resource_count,json=resourceCount,proto3" json:"resource_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionLabRequest) Reset() {
	*x = ProvisionLabRequest{}
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionLabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionLabRequest) ProtoMessage() {}

func (x *ProvisionLabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionLabRequest.ProtoReflect.Descriptor instead.
func (*ProvisionLabRequest) Descriptor() ([]byte, []int) {
	return file_qlab_dev_v1_dev_proto_rawDescGZIP(), []int{1}
}

func (x *ProvisionLabRequest) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *ProvisionLabRequest) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *ProvisionLabRequest) GetResourceCount() int32 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

type ProvisionLabResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lab           *v1.Lab                `protobuf:"bytes,1,opt,name=lab,proto3" json:"lab,omitempty"`
	Pool          *v1.ResourcePool       `protobuf:"bytes,2,opt,name=pool,proto3" json:"pool,omitempty"`
	Members       []*LabMember           `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	Resources     []*v1.Resource         `protobuf:"bytes,4,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionLabResponse) Reset() {
	*x = ProvisionLabResponse{}
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionLabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionLabResponse) ProtoMessage() {}

func (x *ProvisionLabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionLabResponse.ProtoReflect.Descriptor instead.
func (*ProvisionLabResponse) Descriptor() ([]byte, []int) {
	return file_qlab_dev_v1_dev_proto_rawDescGZIP(), []int{2}
}

func (x *ProvisionLabResponse) GetLab() *v1.Lab {
	if x != nil {
		return x.Lab
	}
	return nil
}

func (x *ProvisionLabResponse) GetPool() *v1.ResourcePool {
	if x != nil {
		return x.Pool
	}
	return nil
}

func (x *ProvisionLabResponse) GetMembers() []*LabMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ProvisionLabResponse) GetResources() []*v1.Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

// MintToken issues a real Firebase ID token to act as the given seeded user — the
// "act as anyone without the OAuth dance" primitive. Send it as Authorization:
// Bearer, plus X-QLab-Lab for the lab you're acting in.
type MintTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintTokenRequest) Reset() {
	*x = MintTokenRequest{}
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintTokenRequest) ProtoMessage() {}

func (x *MintTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintTokenRequest.ProtoReflect.Descriptor instead.
func (*MintTokenRequest) Descriptor() ([]byte, []int) {
	return file_qlab_dev_v1_dev_proto_rawDescGZIP(), []int{3}
}

func (x *MintTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MintTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	User          *v1.User               `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintTokenResponse) Reset() {
	*x = MintTokenResponse{}
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintTokenResponse) ProtoMessage() {}

func (x *MintTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintTokenResponse.ProtoReflect.Descriptor instead.
func (*MintTokenResponse) Descriptor() ([]byte, []int) {
	return file_qlab_dev_v1_dev_proto_rawDescGZIP(), []int{4}
}

func (x *MintTokenResponse) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *MintTokenResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

// ListLabs lists demo workspaces, optionally filtered to those whose feature
// (lab name) contains the given substring.
type ListLabsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feature       string                 `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLabsRequest) Reset() {
	*x = ListLabsRequest{}
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLabsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLabsRequest) ProtoMessage() {}

func (x *ListLabsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLabsRequest.ProtoReflect.Descriptor instead.
func (*ListLabsRequest) Descriptor() ([]byte, []int) {
	return file_qlab_dev_v1_dev_proto_rawDescGZIP(), []int{5}
}

func (x *ListLabsRequest) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

type LabSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lab           *v1.Lab                `protobuf:"bytes,1,opt,name=lab,proto3" json:"lab,omitempty"`
	UserCount     int32                  `protobuf:"varint,2,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	ResourceCount int32                  `protobuf:"varint,3,opt,name=resource_count,json=resourceCount,proto3" json:"resource_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabSummary) Reset() {
	*x = LabSummary{}
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabSummary) ProtoMessage() {}

func (x *LabSummary) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabSummary.ProtoReflect.Descriptor instead.
func (*LabSummary) Descriptor() ([]byte, []int) {
	return file_qlab_dev_v1_dev_proto_rawDescGZIP(), []int{6}
}

func (x *LabSummary) GetLab() *v1.Lab {
	if x != nil {
		return x.Lab
	}
	return nil
}

func (x *LabSummary) GetUserCount() int32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *LabSummary) GetResourceCount() int32 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

type ListLabsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labs          []*LabSummary          `protobuf:"bytes,1,rep,name=labs,proto3" json:"labs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLabsResponse) Reset() {
	*x = ListLabsResponse{}
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLabsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLabsResponse) ProtoMessage() {}

func (x *ListLabsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLabsResponse.ProtoReflect.Descriptor instead.
func (*ListLabsResponse) Descriptor() ([]byte, []int) {
	return file_qlab_dev_v1_dev_proto_rawDescGZIP(), []int{7}
}

func (x *ListLabsResponse) GetLabs() []*LabSummary {
	if x != nil {
		return x.Labs
	}
	return nil
}

// GetLab dumps a workspace's full state — members, pools, resources, and the whole
// slot queue — the bounded snapshot for handing to Claude / debugging (the
// state-export from the observability convention).
type GetLabRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabId         string                 `protobuf:"bytes,1,opt,name=lab_id,json=labId,proto3" json:"lab_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLabRequest) Reset() {
	*x = GetLabRequest{}
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLabRequest) ProtoMessage() {}

func (x *GetLabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLabRequest.ProtoReflect.Descriptor instead.
func (*GetLabRequest) Descriptor() ([]byte, []int) {
	return file_qlab_dev_v1_dev_proto_rawDescGZIP(), []int{8}
}

func (x *GetLabRequest) GetLabId() string {
	if x != nil {
		return x.LabId
	}
	return ""
}

type GetLabResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lab           *v1.Lab                `protobuf:"bytes,1,opt,name=lab,proto3" json:"lab,omitempty"`
	Members       []*LabMember           `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	Pools         []*v1.ResourcePool     `protobuf:"bytes,3,rep,name=pools,proto3" json:"pools,omitempty"`
	Resources     []*v1.Resource         `protobuf:"bytes,4,rep,name=resources,proto3" json:"resources,omitempty"`
	Slots         []*v1.Slot             `protobuf:"bytes,5,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLabResponse) Reset() {
	*x = GetLabResponse{}
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLabResponse) ProtoMessage() {}

func (x *GetLabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLabResponse.ProtoReflect.Descriptor instead.
func (*GetLabResponse) Descriptor() ([]byte, []int) {
	return file_qlab_dev_v1_dev_proto_rawDescGZIP(), []int{9}
}

func (x *GetLabResponse) GetLab() *v1.Lab {
	if x != nil {
		return x.Lab
	}
	return nil
}

func (x *GetLabResponse) GetMembers() []*LabMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GetLabResponse) GetPools() []*v1.ResourcePool {
	if x != nil {
		return x.Pools
	}
	return nil
}

func (x *GetLabResponse) GetResources() []*v1.Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *GetLabResponse) GetSlots() []*v1.Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

// TeardownLab deletes a workspace and everything in it (cascade).
type TeardownLabRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabId         string                 `protobuf:"bytes,1,opt,name=lab_id,json=labId,proto3" json:"lab_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeardownLabRequest) Reset() {
	*x = TeardownLabRequest{}
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeardownLabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeardownLabRequest) ProtoMessage() {}

func (x *TeardownLabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeardownLabRequest.ProtoReflect.Descriptor instead.
func (*TeardownLabRequest) Descriptor() ([]byte, []int) {
	return file_qlab_dev_v1_dev_proto_rawDescGZIP(), []int{10}
}

func (x *TeardownLabRequest) GetLabId() string {
	if x != nil {
		return x.LabId
	}
	return ""
}

type TeardownLabResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeardownLabResponse) Reset() {
	*x = TeardownLabResponse{}
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeardownLabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeardownLabResponse) ProtoMessage() {}

func (x *TeardownLabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qlab_dev_v1_dev_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeardownLabResponse.ProtoReflect.Descriptor instead.
func (*TeardownLabResponse) Descriptor() ([]byte, []int) {
	return file_qlab_dev_v1_dev_proto_rawDescGZIP(), []int{11}
}

var File_qlab_dev_v1_dev_proto protoreflect.FileDescriptor

const file_qlab_dev_v1_dev_proto_rawDesc = "" +
	"\n" +
	"\x15qlab/dev/v1/dev.proto\x12\vqlab.dev.v1\x1a\x1bbuf/validate/validate.proto\x1a\x13qlab/v1/types.proto\"T\n" +
	"\tLabMember\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.qlab.v1.UserR\x04user\x12$\n" +
	"\x04role\x18\x02 \x01(\x0e2\x10.qlab.v1.LabRoleR\x04role\"\x9a\x01\n" +
	"\x13ProvisionLabRequest\x12#\n" +
	"\afeature\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\afeature\x12,\n" +
	"\fmember_count\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x04\x182(\x00R\vmemberCount\x120\n" +
	"\x0eresource_count\x18\x03 \x01(\x05B\t\xbaH\x06\x1a\x04\x18\x14(\x01R\rresourceCount\"\xc4\x01\n" +
	"\x14ProvisionLabResponse\x12\x1e\n" +
	"\x03lab\x18\x01 \x01(\v2\f.qlab.v1.LabR\x03lab\x12)\n" +
	"\x04pool\x18\x02 \x01(\v2\x15.qlab.v1.ResourcePoolR\x04pool\x120\n" +
	"\amembers\x18\x03 \x03(\v2\x16.qlab.dev.v1.LabMemberR\amembers\x12/\n" +
	"\tresources\x18\x04 \x03(\v2\x11.qlab.v1.ResourceR\tresources\"5\n" +
	"\x10MintTokenRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\"Q\n" +
	"\x11MintTokenResponse\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\x12!\n" +
	"\x04user\x18\x02 \x01(\v2\r.qlab.v1.UserR\x04user\"4\n" +
	"\x0fListLabsRequest\x12!\n" +
	"\afeature\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x18dR\afeature\"r\n" +
	"\n" +
	"LabSummary\x12\x1e\n" +
	"\x03lab\x18\x01 \x01(\v2\f.qlab.v1.LabR\x03lab\x12\x1d\n" +
	"\n" +
	"user_count\x18\x02 \x01(\x05R\tuserCount\x12%\n" +
	"\x0eresource_count\x18\x03 \x01(\x05R\rresourceCount\"?\n" +
	"\x10ListLabsResponse\x12+\n" +
	"\x04labs\x18\x01 \x03(\v2\x17.qlab.dev.v1.LabSummaryR\x04labs\"0\n" +
	"\rGetLabRequest\x12\x1f\n" +
	"\x06lab_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05labId\"\xe5\x01\n" +
	"\x0eGetLabResponse\x12\x1e\n" +
	"\x03lab\x18\x01 \x01(\v2\f.qlab.v1.LabR\x03lab\x120\n" +
	"\amembers\x18\x02 \x03(\v2\x16.qlab.dev.v1.LabMemberR\amembers\x12+\n" +
	"\x05pools\x18\x03 \x03(\v2\x15.qlab.v1.ResourcePoolR\x05pools\x12/\n" +
	"\tresources\x18\x04 \x03(\v2\x11.qlab.v1.ResourceR\tresources\x12#\n" +
	"\x05slots\x18\x05 \x03(\v2\r.qlab.v1.SlotR\x05slots\"5\n" +
	"\x12TeardownLabRequest\x12\x1f\n" +
	"\x06lab_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05labId\"\x15\n" +
	"\x13TeardownLabResponse2\x8b\x03\n" +
	"\n" +
	"DevService\x12S\n" +
	"\fProvisionLab\x12 .qlab.dev.v1.ProvisionLabRequest\x1a!.qlab.dev.v1.ProvisionLabResponse\x12J\n" +
	"\tMintToken\x12\x1d.qlab.dev.v1.MintTokenRequest\x1a\x1e.qlab.dev.v1.MintTokenResponse\x12G\n" +
	"\bListLabs\x12\x1c.qlab.dev.v1.ListLabsRequest\x1a\x1d.qlab.dev.v1.ListLabsResponse\x12A\n" +
	"\x06GetLab\x12\x1a.qlab.dev.v1.GetLabRequest\x1a\x1b.qlab.dev.v1.GetLabResponse\x12P\n" +
	"\vTeardownLab\x12\x1f.qlab.dev.v1.TeardownLabRequest\x1a .qlab.dev.v1.TeardownLabResponseB\xaf\x01\n" +
	"\x0fcom.qlab.dev.v1B\bDevProtoP\x01ZDgithub.com/tallam99/qlab/backend/internal/protogen/qlab/dev/v1;devv1\xa2\x02\x03QDX\xaa\x02\vQlab.Dev.V1\xca\x02\vQlab\\Dev\\V1\xe2\x02\x17Qlab\\Dev\\V1\\GPBMetadata\xea\x02\rQlab::Dev::V1b\x06proto3"

var (
	file_qlab_dev_v1_dev_proto_rawDescOnce sync.Once
	file_qlab_dev_v1_dev_proto_rawDescData []byte
)

func file_qlab_dev_v1_dev_proto_rawDescGZIP() []byte {
	file_qlab_dev_v1_dev_proto_rawDescOnce.Do(func() {
		file_qlab_dev_v1_dev_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qlab_dev_v1_dev_proto_rawDesc), len(file_qlab_dev_v1_dev_proto_rawDesc)))
	})
	return file_qlab_dev_v1_dev_proto_rawDescData
}

var file_qlab_dev_v1_dev_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_qlab_dev_v1_dev_proto_goTypes = []any{
	(*LabMember)(nil),            // 0: qlab.dev.v1.LabMember
	(*ProvisionLabRequest)(nil),  // 1: qlab.dev.v1.ProvisionLabRequest
	(*ProvisionLabResponse)(nil), // 2: qlab.dev.v1.ProvisionLabResponse
	(*MintTokenRequest)(nil),     // 3: qlab.dev.v1.MintTokenRequest
	(*MintTokenResponse)(nil),    // 4: qlab.dev.v1.MintTokenResponse
	(*ListLabsRequest)(nil),      // 5: qlab.dev.v1.ListLabsRequest
	(*LabSummary)(nil),           // 6: qlab.dev.v1.LabSummary
	(*ListLabsResponse)(nil),     // 7: qlab.dev.v1.ListLabsResponse
	(*GetLabRequest)(nil),        // 8: qlab.dev.v1.GetLabRequest
	(*GetLabResponse)(nil),       // 9: qlab.dev.v1.GetLabResponse
	(*TeardownLabRequest)(nil),   // 10: qlab.dev.v1.TeardownLabRequest
	(*TeardownLabResponse)(nil),  // 11: qlab.dev.v1.TeardownLabResponse
	(*v1.User)(nil),              // 12: qlab.v1.User
	(v1.LabRole)(0),              // 13: qlab.v1.LabRole
	(*v1.Lab)(nil),               // 14: qlab.v1.Lab
	(*v1.ResourcePool)(nil),      // 15: qlab.v1.ResourcePool
	(*v1.Resource)(nil),          // 16: qlab.v1.Resource
	(*v1.Slot)(nil),              // 17: qlab.v1.Slot
}
var file_qlab_dev_v1_dev_proto_depIdxs = []int32{
	12, // 0: qlab.dev.v1.LabMember.user:type_name -> qlab.v1.User
	13, // 1: qlab.dev.v1.LabMember.role:type_name -> qlab.v1.LabRole
	14, // 2: qlab.dev.v1.ProvisionLabResponse.lab:type_name -> qlab.v1.Lab
	15, // 3: qlab.dev.v1.ProvisionLabResponse.pool:type_name -> qlab.v1.ResourcePool
	0,  // 4: qlab.dev.v1.ProvisionLabResponse.members:type_name -> qlab.dev.v1.LabMember
	16, // 5: qlab.dev.v1.ProvisionLabResponse.resources:type_name -> qlab.v1.Resource
	12, // 6: qlab.dev.v1.MintTokenResponse.user:type_name -> qlab.v1.User
	14, // 7: qlab.dev.v1.LabSummary.lab:type_name -> qlab.v1.Lab
	6,  // 8: qlab.dev.v1.ListLabsResponse.labs:type_name -> qlab.dev.v1.LabSummary
	14, // 9: qlab.dev.v1.GetLabResponse.lab:type_name -> qlab.v1.Lab
	0,  // 10: qlab.dev.v1.GetLabResponse.members:type_name -> qlab.dev.v1.LabMember
	15, // 11: qlab.dev.v1.GetLabResponse.pools:type_name -> qlab.v1.ResourcePool
	16, // 12: qlab.dev.v1.GetLabResponse.resources:type_name -> qlab.v1.Resource
	17, // 13: qlab.dev.v1.GetLabResponse.slots:type_name -> qlab.v1.Slot
	1,  // 14: qlab.dev.v1.DevService.ProvisionLab:input_type -> qlab.dev.v1.ProvisionLabRequest
	3,  // 15: qlab.dev.v1.DevService.MintToken:input_type -> qlab.dev.v1.MintTokenRequest
	5,  // 16: qlab.dev.v1.DevService.ListLabs:input_type -> qlab.dev.v1.ListLabsRequest
	8,  // 17: qlab.dev.v1.DevService.GetLab:input_type -> qlab.dev.v1.GetLabRequest
	10, // 18: qlab.dev.v1.DevService.TeardownLab:input_type -> qlab.dev.v1.TeardownLabRequest
	2,  // 19: qlab.dev.v1.DevService.ProvisionLab:output_type -> qlab.dev.v1.ProvisionLabResponse
	4,  // 20: qlab.dev.v1.DevService.MintToken:output_type -> qlab.dev.v1.MintTokenResponse
	7,  // 21: qlab.dev.v1.DevService.ListLabs:output_type -> qlab.dev.v1.ListLabsResponse
	9,  // 22: qlab.dev.v1.DevService.GetLab:output_type -> qlab.dev.v1.GetLabResponse
	11, // 23: qlab.dev.v1.DevService.TeardownLab:output_type -> qlab.dev.v1.TeardownLabResponse
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_qlab_dev_v1_dev_proto_init() }
func file_qlab_dev_v1_dev_proto_init() {
	if File_qlab_dev_v1_dev_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qlab_dev_v1_dev_proto_rawDesc), len(file_qlab_dev_v1_dev_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qlab_dev_v1_dev_proto_goTypes,
		DependencyIndexes: file_qlab_dev_v1_dev_proto_depIdxs,
		MessageInfos:      file_qlab_dev_v1_dev_proto_msgTypes,
	}.Build()
	File_qlab_dev_v1_dev_proto = out.File
	file_qlab_dev_v1_dev_proto_goTypes = nil
	file_qlab_dev_v1_dev_proto_depIdxs = nil
}
