// Code generated by "enumer -type=Environment -trimprefix=Env -transform=lower -output=environment_enumer.go"; DO NOT EDIT.

package config

import (
	"fmt"
	"strings"
)

const _EnvironmentName = "unknownlocalstagingproduction"

var _EnvironmentIndex = [...]uint8{0, 7, 12, 19, 29}

const _EnvironmentLowerName = "unknownlocalstagingproduction"

func (i Environment) String() string {
	if i < 0 || i >= Environment(len(_EnvironmentIndex)-1) {
		return fmt.Sprintf("Environment(%d)", i)
	}
	return _EnvironmentName[_EnvironmentIndex[i]:_EnvironmentIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EnvironmentNoOp() {
	var x [1]struct{}
	_ = x[EnvUnknown-(0)]
	_ = x[EnvLocal-(1)]
	_ = x[EnvStaging-(2)]
	_ = x[EnvProduction-(3)]
}

var _EnvironmentValues = []Environment{EnvUnknown, EnvLocal, EnvStaging, EnvProduction}

var _EnvironmentNameToValueMap = map[string]Environment{
	_EnvironmentName[0:7]:        EnvUnknown,
	_EnvironmentLowerName[0:7]:   EnvUnknown,
	_EnvironmentName[7:12]:       EnvLocal,
	_EnvironmentLowerName[7:12]:  EnvLocal,
	_EnvironmentName[12:19]:      EnvStaging,
	_EnvironmentLowerName[12:19]: EnvStaging,
	_EnvironmentName[19:29]:      EnvProduction,
	_EnvironmentLowerName[19:29]: EnvProduction,
}

var _EnvironmentNames = []string{
	_EnvironmentName[0:7],
	_EnvironmentName[7:12],
	_EnvironmentName[12:19],
	_EnvironmentName[19:29],
}

// EnvironmentString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EnvironmentString(s string) (Environment, error) {
	if val, ok := _EnvironmentNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EnvironmentNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Environment values", s)
}

// EnvironmentValues returns all values of the enum
func EnvironmentValues() []Environment {
	return _EnvironmentValues
}

// EnvironmentStrings returns a slice of all String values of the enum
func EnvironmentStrings() []string {
	strs := make([]string, len(_EnvironmentNames))
	copy(strs, _EnvironmentNames)
	return strs
}

// IsAEnvironment returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Environment) IsAEnvironment() bool {
	for _, v := range _EnvironmentValues {
		if i == v {
			return true
		}
	}
	return false
}
