// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type LabRole string

const (
	LabRoleHEAD   LabRole = "HEAD"
	LabRoleMEMBER LabRole = "MEMBER"
)

func (e *LabRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LabRole(s)
	case string:
		*e = LabRole(s)
	default:
		return fmt.Errorf("unsupported scan type for LabRole: %T", src)
	}
	return nil
}

type NullLabRole struct {
	LabRole LabRole
	Valid   bool // Valid is true if LabRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLabRole) Scan(value interface{}) error {
	if value == nil {
		ns.LabRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LabRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLabRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LabRole), nil
}

type OutboxStatus string

const (
	OutboxStatusPENDING OutboxStatus = "PENDING"
	OutboxStatusSENT    OutboxStatus = "SENT"
	OutboxStatusDEAD    OutboxStatus = "DEAD"
)

func (e *OutboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatus(s)
	case string:
		*e = OutboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatus: %T", src)
	}
	return nil
}

type NullOutboxStatus struct {
	OutboxStatus OutboxStatus
	Valid        bool // Valid is true if OutboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatus), nil
}

type ResourceKind string

const (
	ResourceKindVENTHOOD ResourceKind = "VENT_HOOD"
)

func (e *ResourceKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceKind(s)
	case string:
		*e = ResourceKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceKind: %T", src)
	}
	return nil
}

type NullResourceKind struct {
	ResourceKind ResourceKind
	Valid        bool // Valid is true if ResourceKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceKind) Scan(value interface{}) error {
	if value == nil {
		ns.ResourceKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceKind), nil
}

type SlotStatus string

const (
	SlotStatusSCHEDULED SlotStatus = "SCHEDULED"
	SlotStatusACTIVE    SlotStatus = "ACTIVE"
	SlotStatusCOMPLETE  SlotStatus = "COMPLETE"
	SlotStatusCANCELLED SlotStatus = "CANCELLED"
	SlotStatusNOSHOW    SlotStatus = "NO_SHOW"
)

func (e *SlotStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SlotStatus(s)
	case string:
		*e = SlotStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SlotStatus: %T", src)
	}
	return nil
}

type NullSlotStatus struct {
	SlotStatus SlotStatus
	Valid      bool // Valid is true if SlotStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSlotStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SlotStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SlotStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSlotStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SlotStatus), nil
}

type Lab struct {
	LabsID    uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	CreatedBy *uuid.UUID
	UpdatedBy *uuid.UUID
}

type LabsUser struct {
	LabsID    uuid.UUID
	UsersID   uuid.UUID
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
	CreatedBy *uuid.UUID
	UpdatedBy *uuid.UUID
}

type Outbox struct {
	OutboxID        uuid.UUID
	LabsID          uuid.UUID
	DedupKey        string
	EventType       string
	Payload         []byte
	Status          string
	Attempts        int32
	LastError       pgtype.Text
	AvailableAt     time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatedBy       *uuid.UUID
	UpdatedBy       *uuid.UUID
	RecipientUserID *uuid.UUID
}

type Resource struct {
	ResourcesID     uuid.UUID
	ResourcePoolsID uuid.UUID
	LabsID          uuid.UUID
	Kind            string
	Name            string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatedBy       *uuid.UUID
	UpdatedBy       *uuid.UUID
}

type ResourcePool struct {
	ResourcePoolsID uuid.UUID
	LabsID          uuid.UUID
	Kind            string
	Name            string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatedBy       *uuid.UUID
	UpdatedBy       *uuid.UUID
}

type Slot struct {
	SlotsID         uuid.UUID
	LabsID          uuid.UUID
	UsersID         uuid.UUID
	ResourcePoolsID uuid.UUID
	ResourcesID     *uuid.UUID
	SlotPriority    int64
	DesiredStart    time.Time
	Lookahead       int32
	Duration        int32
	CommittedStart  *time.Time
	ActualStart     *time.Time
	Status          string
	Note            string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatedBy       *uuid.UUID
	UpdatedBy       *uuid.UUID
}

type User struct {
	UsersID     uuid.UUID
	FirebaseUid pgtype.Text
	Email       string
	FirstName   string
	LastName    string
	Dob         pgtype.Date
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedBy   *uuid.UUID
	UpdatedBy   *uuid.UUID
}
