// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLabs = `-- name: CountLabs :one

SELECT count(*) FROM labs
`

// Static queries for the QLab store, compiled to type-safe Go by sqlc (see
// sqlc.yaml; regenerate with `mage genSqlc`). Transaction control — the per-event
// SET LOCAL app.current_lab_id and the pool advisory lock — stays hand-written in
// pool.go, since it is plumbing rather than data access.
func (q *Queries) CountLabs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLabs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLab = `-- name: CreateLab :one

INSERT INTO labs (labs_id, name, created_by, updated_by)
VALUES ($1, $2, $3, $3)
RETURNING labs_id, name
`

type CreateLabParams struct {
	LabsID uuid.UUID
	Name   string
	Actor  *uuid.UUID
}

type CreateLabRow struct {
	LabsID uuid.UUID
	Name   string
}

// Operator tooling (staging/local only; runs on an elevated, RLS-bypassing
// connection). These are cross-tenant admin queries — see store.OperatorStore.
func (q *Queries) CreateLab(ctx context.Context, arg CreateLabParams) (CreateLabRow, error) {
	row := q.db.QueryRow(ctx, createLab, arg.LabsID, arg.Name, arg.Actor)
	var i CreateLabRow
	err := row.Scan(&i.LabsID, &i.Name)
	return i, err
}

const createMembership = `-- name: CreateMembership :exec
INSERT INTO labs_users (labs_id, users_id, role, created_by, updated_by)
VALUES ($1, $2, $3::lab_role, $4, $4)
`

type CreateMembershipParams struct {
	LabsID  uuid.UUID
	UsersID uuid.UUID
	Role    string
	Actor   *uuid.UUID
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership,
		arg.LabsID,
		arg.UsersID,
		arg.Role,
		arg.Actor,
	)
	return err
}

const createResource = `-- name: CreateResource :one
INSERT INTO resources (resources_id, resource_pools_id, labs_id, kind, name, created_by, updated_by)
VALUES ($1, $2, $3, $4::resource_kind, $5, $6, $6)
RETURNING resources_id, resource_pools_id, labs_id, kind, name
`

type CreateResourceParams struct {
	ResourcesID     uuid.UUID
	ResourcePoolsID uuid.UUID
	LabsID          uuid.UUID
	Kind            string
	Name            string
	Actor           *uuid.UUID
}

type CreateResourceRow struct {
	ResourcesID     uuid.UUID
	ResourcePoolsID uuid.UUID
	LabsID          uuid.UUID
	Kind            string
	Name            string
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (CreateResourceRow, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.ResourcesID,
		arg.ResourcePoolsID,
		arg.LabsID,
		arg.Kind,
		arg.Name,
		arg.Actor,
	)
	var i CreateResourceRow
	err := row.Scan(
		&i.ResourcesID,
		&i.ResourcePoolsID,
		&i.LabsID,
		&i.Kind,
		&i.Name,
	)
	return i, err
}

const createResourcePool = `-- name: CreateResourcePool :one
INSERT INTO resource_pools (resource_pools_id, labs_id, kind, name, created_by, updated_by)
VALUES ($1, $2, $3::resource_kind, $4, $5, $5)
RETURNING resource_pools_id, labs_id, kind, name
`

type CreateResourcePoolParams struct {
	ResourcePoolsID uuid.UUID
	LabsID          uuid.UUID
	Kind            string
	Name            string
	Actor           *uuid.UUID
}

type CreateResourcePoolRow struct {
	ResourcePoolsID uuid.UUID
	LabsID          uuid.UUID
	Kind            string
	Name            string
}

func (q *Queries) CreateResourcePool(ctx context.Context, arg CreateResourcePoolParams) (CreateResourcePoolRow, error) {
	row := q.db.QueryRow(ctx, createResourcePool,
		arg.ResourcePoolsID,
		arg.LabsID,
		arg.Kind,
		arg.Name,
		arg.Actor,
	)
	var i CreateResourcePoolRow
	err := row.Scan(
		&i.ResourcePoolsID,
		&i.LabsID,
		&i.Kind,
		&i.Name,
	)
	return i, err
}

const createUserWithEmail = `-- name: CreateUserWithEmail :one
INSERT INTO users (users_id, email, first_name, last_name, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $5)
RETURNING users_id, firebase_uid, email, first_name, last_name
`

type CreateUserWithEmailParams struct {
	UsersID   uuid.UUID
	Email     string
	FirstName string
	LastName  string
	Actor     *uuid.UUID
}

type CreateUserWithEmailRow struct {
	UsersID     uuid.UUID
	FirebaseUid *string
	Email       string
	FirstName   string
	LastName    string
}

func (q *Queries) CreateUserWithEmail(ctx context.Context, arg CreateUserWithEmailParams) (CreateUserWithEmailRow, error) {
	row := q.db.QueryRow(ctx, createUserWithEmail,
		arg.UsersID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Actor,
	)
	var i CreateUserWithEmailRow
	err := row.Scan(
		&i.UsersID,
		&i.FirebaseUid,
		&i.Email,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const deleteLab = `-- name: DeleteLab :execrows
DELETE FROM labs WHERE labs_id = $1
`

func (q *Queries) DeleteLab(ctx context.Context, labsID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLab, labsID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (labs_id, dedup_key, event_type, payload, recipient_user_id, created_by, updated_by)
VALUES ($1, $2, $3, $4::jsonb, $5, $6, $6)
ON CONFLICT (dedup_key) DO NOTHING
`

type InsertOutboxParams struct {
	LabsID          uuid.UUID
	DedupKey        string
	EventType       string
	Payload         []byte
	RecipientUserID *uuid.UUID
	Actor           *uuid.UUID
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox,
		arg.LabsID,
		arg.DedupKey,
		arg.EventType,
		arg.Payload,
		arg.RecipientUserID,
		arg.Actor,
	)
	return err
}

const isMember = `-- name: IsMember :one
SELECT EXISTS (
    SELECT 1 FROM labs_users WHERE labs_id = $1 AND users_id = $2
)
`

type IsMemberParams struct {
	LabsID  uuid.UUID
	UsersID uuid.UUID
}

func (q *Queries) IsMember(ctx context.Context, arg IsMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMember, arg.LabsID, arg.UsersID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const labByID = `-- name: LabByID :one
SELECT labs_id, name FROM labs WHERE labs_id = $1
`

type LabByIDRow struct {
	LabsID uuid.UUID
	Name   string
}

func (q *Queries) LabByID(ctx context.Context, labsID uuid.UUID) (LabByIDRow, error) {
	row := q.db.QueryRow(ctx, labByID, labsID)
	var i LabByIDRow
	err := row.Scan(&i.LabsID, &i.Name)
	return i, err
}

const linkFirebaseUID = `-- name: LinkFirebaseUID :one
UPDATE users SET
    firebase_uid = $1::text,
    first_name   = COALESCE(NULLIF($2::text, ''), first_name),
    last_name    = COALESCE(NULLIF($3::text, ''), last_name),
    updated_by   = $4,
    updated_at   = now()
WHERE users_id = $5 AND firebase_uid IS NULL
RETURNING users_id, firebase_uid, email, first_name, last_name
`

type LinkFirebaseUIDParams struct {
	FirebaseUid string
	FirstName   string
	LastName    string
	Actor       *uuid.UUID
	UsersID     uuid.UUID
}

type LinkFirebaseUIDRow struct {
	UsersID     uuid.UUID
	FirebaseUid *string
	Email       string
	FirstName   string
	LastName    string
}

// First-login provisioning: bind a Firebase uid to an existing UNLINKED user row and
// fill any name parts the invite left blank (keep an existing name if the provider
// sent none). The user is recorded as their own updater. The firebase_uid IS NULL
// guard makes the write self-protecting: a concurrent first login for the same row
// updates zero rows (no row returned) rather than racing to rebind an already-linked
// identity.
func (q *Queries) LinkFirebaseUID(ctx context.Context, arg LinkFirebaseUIDParams) (LinkFirebaseUIDRow, error) {
	row := q.db.QueryRow(ctx, linkFirebaseUID,
		arg.FirebaseUid,
		arg.FirstName,
		arg.LastName,
		arg.Actor,
		arg.UsersID,
	)
	var i LinkFirebaseUIDRow
	err := row.Scan(
		&i.UsersID,
		&i.FirebaseUid,
		&i.Email,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const listLabMembers = `-- name: ListLabMembers :many
SELECT u.users_id, u.firebase_uid, u.email, u.first_name, u.last_name, lu.role
FROM labs_users lu JOIN users u ON u.users_id = lu.users_id
WHERE lu.labs_id = $1
ORDER BY lu.role, u.email
`

type ListLabMembersRow struct {
	UsersID     uuid.UUID
	FirebaseUid *string
	Email       string
	FirstName   string
	LastName    string
	Role        string
}

func (q *Queries) ListLabMembers(ctx context.Context, labsID uuid.UUID) ([]ListLabMembersRow, error) {
	rows, err := q.db.Query(ctx, listLabMembers, labsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabMembersRow{}
	for rows.Next() {
		var i ListLabMembersRow
		if err := rows.Scan(
			&i.UsersID,
			&i.FirebaseUid,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabResourcePools = `-- name: ListLabResourcePools :many
SELECT resource_pools_id, labs_id, kind, name FROM resource_pools
WHERE labs_id = $1 ORDER BY name, resource_pools_id
`

type ListLabResourcePoolsRow struct {
	ResourcePoolsID uuid.UUID
	LabsID          uuid.UUID
	Kind            string
	Name            string
}

func (q *Queries) ListLabResourcePools(ctx context.Context, labsID uuid.UUID) ([]ListLabResourcePoolsRow, error) {
	rows, err := q.db.Query(ctx, listLabResourcePools, labsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabResourcePoolsRow{}
	for rows.Next() {
		var i ListLabResourcePoolsRow
		if err := rows.Scan(
			&i.ResourcePoolsID,
			&i.LabsID,
			&i.Kind,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabResources = `-- name: ListLabResources :many
SELECT resources_id, resource_pools_id, labs_id, kind, name FROM resources
WHERE labs_id = $1 ORDER BY name, resources_id
`

type ListLabResourcesRow struct {
	ResourcesID     uuid.UUID
	ResourcePoolsID uuid.UUID
	LabsID          uuid.UUID
	Kind            string
	Name            string
}

func (q *Queries) ListLabResources(ctx context.Context, labsID uuid.UUID) ([]ListLabResourcesRow, error) {
	rows, err := q.db.Query(ctx, listLabResources, labsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabResourcesRow{}
	for rows.Next() {
		var i ListLabResourcesRow
		if err := rows.Scan(
			&i.ResourcesID,
			&i.ResourcePoolsID,
			&i.LabsID,
			&i.Kind,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabSlots = `-- name: ListLabSlots :many
SELECT slots_id, labs_id, users_id, resource_pools_id, resources_id,
       slot_priority, status, desired_start, lookahead, duration,
       committed_start, actual_start, note
FROM slots WHERE labs_id = $1
ORDER BY resource_pools_id, slot_priority, slots_id
`

type ListLabSlotsRow struct {
	SlotsID         uuid.UUID
	LabsID          uuid.UUID
	UsersID         uuid.UUID
	ResourcePoolsID uuid.UUID
	ResourcesID     *uuid.UUID
	SlotPriority    int64
	Status          string
	DesiredStart    time.Time
	Lookahead       int32
	Duration        int32
	CommittedStart  *time.Time
	ActualStart     *time.Time
	Note            string
}

func (q *Queries) ListLabSlots(ctx context.Context, labsID uuid.UUID) ([]ListLabSlotsRow, error) {
	rows, err := q.db.Query(ctx, listLabSlots, labsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabSlotsRow{}
	for rows.Next() {
		var i ListLabSlotsRow
		if err := rows.Scan(
			&i.SlotsID,
			&i.LabsID,
			&i.UsersID,
			&i.ResourcePoolsID,
			&i.ResourcesID,
			&i.SlotPriority,
			&i.Status,
			&i.DesiredStart,
			&i.Lookahead,
			&i.Duration,
			&i.CommittedStart,
			&i.ActualStart,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabsWithCounts = `-- name: ListLabsWithCounts :many
SELECT l.labs_id, l.name,
       (SELECT count(*) FROM labs_users lu WHERE lu.labs_id = l.labs_id) AS user_count,
       (SELECT count(*) FROM resources r WHERE r.labs_id = l.labs_id) AS resource_count
FROM labs l
WHERE $1::text = '' OR l.name ILIKE '%' || $1 || '%'
ORDER BY l.name, l.labs_id
`

type ListLabsWithCountsRow struct {
	LabsID        uuid.UUID
	Name          string
	UserCount     int64
	ResourceCount int64
}

func (q *Queries) ListLabsWithCounts(ctx context.Context, feature string) ([]ListLabsWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listLabsWithCounts, feature)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabsWithCountsRow{}
	for rows.Next() {
		var i ListLabsWithCountsRow
		if err := rows.Scan(
			&i.LabsID,
			&i.Name,
			&i.UserCount,
			&i.ResourceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSlotsForUpdate = `-- name: ListLiveSlotsForUpdate :many
SELECT slots_id, labs_id, users_id, resource_pools_id, resources_id,
       slot_priority, status, desired_start, lookahead, duration,
       committed_start, actual_start, note
FROM slots
WHERE labs_id = $1 AND resource_pools_id = $2 AND status IN ('SCHEDULED', 'ACTIVE')
ORDER BY slot_priority
FOR UPDATE
`

type ListLiveSlotsForUpdateParams struct {
	LabsID          uuid.UUID
	ResourcePoolsID uuid.UUID
}

type ListLiveSlotsForUpdateRow struct {
	SlotsID         uuid.UUID
	LabsID          uuid.UUID
	UsersID         uuid.UUID
	ResourcePoolsID uuid.UUID
	ResourcesID     *uuid.UUID
	SlotPriority    int64
	Status          string
	DesiredStart    time.Time
	Lookahead       int32
	Duration        int32
	CommittedStart  *time.Time
	ActualStart     *time.Time
	Note            string
}

func (q *Queries) ListLiveSlotsForUpdate(ctx context.Context, arg ListLiveSlotsForUpdateParams) ([]ListLiveSlotsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listLiveSlotsForUpdate, arg.LabsID, arg.ResourcePoolsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveSlotsForUpdateRow{}
	for rows.Next() {
		var i ListLiveSlotsForUpdateRow
		if err := rows.Scan(
			&i.SlotsID,
			&i.LabsID,
			&i.UsersID,
			&i.ResourcePoolsID,
			&i.ResourcesID,
			&i.SlotPriority,
			&i.Status,
			&i.DesiredStart,
			&i.Lookahead,
			&i.Duration,
			&i.CommittedStart,
			&i.ActualStart,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
SELECT resources_id, resource_pools_id, labs_id, kind, name
FROM resources
WHERE labs_id = $1 AND resource_pools_id = $2
ORDER BY resources_id
`

type ListResourcesParams struct {
	LabsID          uuid.UUID
	ResourcePoolsID uuid.UUID
}

type ListResourcesRow struct {
	ResourcesID     uuid.UUID
	ResourcePoolsID uuid.UUID
	LabsID          uuid.UUID
	Kind            string
	Name            string
}

func (q *Queries) ListResources(ctx context.Context, arg ListResourcesParams) ([]ListResourcesRow, error) {
	rows, err := q.db.Query(ctx, listResources, arg.LabsID, arg.ResourcePoolsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourcesRow{}
	for rows.Next() {
		var i ListResourcesRow
		if err := rows.Scan(
			&i.ResourcesID,
			&i.ResourcePoolsID,
			&i.LabsID,
			&i.Kind,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlots = `-- name: ListSlots :many
SELECT slots_id, labs_id, users_id, resource_pools_id, resources_id,
       slot_priority, status, desired_start, lookahead, duration,
       committed_start, actual_start, note
FROM slots
WHERE labs_id = $1 AND resource_pools_id = $2
ORDER BY desired_start, slots_id
`

type ListSlotsParams struct {
	LabsID          uuid.UUID
	ResourcePoolsID uuid.UUID
}

type ListSlotsRow struct {
	SlotsID         uuid.UUID
	LabsID          uuid.UUID
	UsersID         uuid.UUID
	ResourcePoolsID uuid.UUID
	ResourcesID     *uuid.UUID
	SlotPriority    int64
	Status          string
	DesiredStart    time.Time
	Lookahead       int32
	Duration        int32
	CommittedStart  *time.Time
	ActualStart     *time.Time
	Note            string
}

func (q *Queries) ListSlots(ctx context.Context, arg ListSlotsParams) ([]ListSlotsRow, error) {
	rows, err := q.db.Query(ctx, listSlots, arg.LabsID, arg.ResourcePoolsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSlotsRow{}
	for rows.Next() {
		var i ListSlotsRow
		if err := rows.Scan(
			&i.SlotsID,
			&i.LabsID,
			&i.UsersID,
			&i.ResourcePoolsID,
			&i.ResourcesID,
			&i.SlotPriority,
			&i.Status,
			&i.DesiredStart,
			&i.Lookahead,
			&i.Duration,
			&i.CommittedStart,
			&i.ActualStart,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resourcePoolByID = `-- name: ResourcePoolByID :one
SELECT resource_pools_id, labs_id, kind, name
FROM resource_pools
WHERE labs_id = $1 AND resource_pools_id = $2
`

type ResourcePoolByIDParams struct {
	LabsID          uuid.UUID
	ResourcePoolsID uuid.UUID
}

type ResourcePoolByIDRow struct {
	ResourcePoolsID uuid.UUID
	LabsID          uuid.UUID
	Kind            string
	Name            string
}

func (q *Queries) ResourcePoolByID(ctx context.Context, arg ResourcePoolByIDParams) (ResourcePoolByIDRow, error) {
	row := q.db.QueryRow(ctx, resourcePoolByID, arg.LabsID, arg.ResourcePoolsID)
	var i ResourcePoolByIDRow
	err := row.Scan(
		&i.ResourcePoolsID,
		&i.LabsID,
		&i.Kind,
		&i.Name,
	)
	return i, err
}

const slotByID = `-- name: SlotByID :one
SELECT slots_id, labs_id, users_id, resource_pools_id, resources_id,
       slot_priority, status, desired_start, lookahead, duration,
       committed_start, actual_start, note
FROM slots
WHERE labs_id = $1 AND slots_id = $2
`

type SlotByIDParams struct {
	LabsID  uuid.UUID
	SlotsID uuid.UUID
}

type SlotByIDRow struct {
	SlotsID         uuid.UUID
	LabsID          uuid.UUID
	UsersID         uuid.UUID
	ResourcePoolsID uuid.UUID
	ResourcesID     *uuid.UUID
	SlotPriority    int64
	Status          string
	DesiredStart    time.Time
	Lookahead       int32
	Duration        int32
	CommittedStart  *time.Time
	ActualStart     *time.Time
	Note            string
}

func (q *Queries) SlotByID(ctx context.Context, arg SlotByIDParams) (SlotByIDRow, error) {
	row := q.db.QueryRow(ctx, slotByID, arg.LabsID, arg.SlotsID)
	var i SlotByIDRow
	err := row.Scan(
		&i.SlotsID,
		&i.LabsID,
		&i.UsersID,
		&i.ResourcePoolsID,
		&i.ResourcesID,
		&i.SlotPriority,
		&i.Status,
		&i.DesiredStart,
		&i.Lookahead,
		&i.Duration,
		&i.CommittedStart,
		&i.ActualStart,
		&i.Note,
	)
	return i, err
}

const upsertSlot = `-- name: UpsertSlot :exec
INSERT INTO slots (
    slots_id, labs_id, users_id, resource_pools_id, resources_id,
    slot_priority, desired_start, lookahead, duration,
    committed_start, actual_start, status, note, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12::slot_status, $13, $14, $14
)
ON CONFLICT (slots_id) DO UPDATE SET
    resources_id      = EXCLUDED.resources_id,
    resource_pools_id = EXCLUDED.resource_pools_id,
    slot_priority     = EXCLUDED.slot_priority,
    desired_start     = EXCLUDED.desired_start,
    lookahead         = EXCLUDED.lookahead,
    duration          = EXCLUDED.duration,
    committed_start   = EXCLUDED.committed_start,
    actual_start      = EXCLUDED.actual_start,
    status            = EXCLUDED.status,
    note              = EXCLUDED.note,
    updated_by        = EXCLUDED.updated_by
`

type UpsertSlotParams struct {
	SlotsID         uuid.UUID
	LabsID          uuid.UUID
	UsersID         uuid.UUID
	ResourcePoolsID uuid.UUID
	ResourcesID     *uuid.UUID
	SlotPriority    int64
	DesiredStart    time.Time
	Lookahead       int32
	Duration        int32
	CommittedStart  *time.Time
	ActualStart     *time.Time
	Status          string
	Note            string
	Actor           *uuid.UUID
}

func (q *Queries) UpsertSlot(ctx context.Context, arg UpsertSlotParams) error {
	_, err := q.db.Exec(ctx, upsertSlot,
		arg.SlotsID,
		arg.LabsID,
		arg.UsersID,
		arg.ResourcePoolsID,
		arg.ResourcesID,
		arg.SlotPriority,
		arg.DesiredStart,
		arg.Lookahead,
		arg.Duration,
		arg.CommittedStart,
		arg.ActualStart,
		arg.Status,
		arg.Note,
		arg.Actor,
	)
	return err
}

const userByEmail = `-- name: UserByEmail :one
SELECT users_id, firebase_uid, email, first_name, last_name
FROM users WHERE email = $1
`

type UserByEmailRow struct {
	UsersID     uuid.UUID
	FirebaseUid *string
	Email       string
	FirstName   string
	LastName    string
}

func (q *Queries) UserByEmail(ctx context.Context, email string) (UserByEmailRow, error) {
	row := q.db.QueryRow(ctx, userByEmail, email)
	var i UserByEmailRow
	err := row.Scan(
		&i.UsersID,
		&i.FirebaseUid,
		&i.Email,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const userByFirebaseUID = `-- name: UserByFirebaseUID :one
SELECT users_id, firebase_uid, email, first_name, last_name
FROM users WHERE firebase_uid = $1::text
`

type UserByFirebaseUIDRow struct {
	UsersID     uuid.UUID
	FirebaseUid *string
	Email       string
	FirstName   string
	LastName    string
}

func (q *Queries) UserByFirebaseUID(ctx context.Context, firebaseUid string) (UserByFirebaseUIDRow, error) {
	row := q.db.QueryRow(ctx, userByFirebaseUID, firebaseUid)
	var i UserByFirebaseUIDRow
	err := row.Scan(
		&i.UsersID,
		&i.FirebaseUid,
		&i.Email,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT users_id, firebase_uid, email, first_name, last_name FROM users WHERE users_id = $1
`

type UserByIDRow struct {
	UsersID     uuid.UUID
	FirebaseUid *string
	Email       string
	FirstName   string
	LastName    string
}

func (q *Queries) UserByID(ctx context.Context, usersID uuid.UUID) (UserByIDRow, error) {
	row := q.db.QueryRow(ctx, userByID, usersID)
	var i UserByIDRow
	err := row.Scan(
		&i.UsersID,
		&i.FirebaseUid,
		&i.Email,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}
