// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLabs = `-- name: CountLabs :one

SELECT count(*) FROM labs
`

// Static queries for the QLab store, compiled to type-safe Go by sqlc (see
// sqlc.yaml; regenerate with `mage genSqlc`). Transaction control — the per-event
// SET LOCAL app.current_lab_id and the pool advisory lock — stays hand-written in
// pool.go, since it is plumbing rather than data access.
func (q *Queries) CountLabs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLabs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (labs_id, dedup_key, event_type, payload, recipient_user_id, created_by, updated_by)
VALUES ($1, $2, $3, $4::jsonb, $5, $6, $6)
ON CONFLICT (dedup_key) DO NOTHING
`

type InsertOutboxParams struct {
	LabsID          uuid.UUID
	DedupKey        string
	EventType       string
	Payload         []byte
	RecipientUserID *uuid.UUID
	Actor           *uuid.UUID
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox,
		arg.LabsID,
		arg.DedupKey,
		arg.EventType,
		arg.Payload,
		arg.RecipientUserID,
		arg.Actor,
	)
	return err
}

const isMember = `-- name: IsMember :one
SELECT EXISTS (
    SELECT 1 FROM labs_users WHERE labs_id = $1 AND users_id = $2
)
`

type IsMemberParams struct {
	LabsID  uuid.UUID
	UsersID uuid.UUID
}

func (q *Queries) IsMember(ctx context.Context, arg IsMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMember, arg.LabsID, arg.UsersID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listLiveSlotsForUpdate = `-- name: ListLiveSlotsForUpdate :many
SELECT slots_id, labs_id, users_id, resource_pools_id, resources_id,
       slot_priority, status, desired_start, lookahead, duration,
       committed_start, actual_start, note
FROM slots
WHERE labs_id = $1 AND resource_pools_id = $2 AND status IN ('SCHEDULED', 'ACTIVE')
ORDER BY slot_priority
FOR UPDATE
`

type ListLiveSlotsForUpdateParams struct {
	LabsID          uuid.UUID
	ResourcePoolsID uuid.UUID
}

type ListLiveSlotsForUpdateRow struct {
	SlotsID         uuid.UUID
	LabsID          uuid.UUID
	UsersID         uuid.UUID
	ResourcePoolsID uuid.UUID
	ResourcesID     *uuid.UUID
	SlotPriority    int64
	Status          string
	DesiredStart    time.Time
	Lookahead       int32
	Duration        int32
	CommittedStart  *time.Time
	ActualStart     *time.Time
	Note            string
}

func (q *Queries) ListLiveSlotsForUpdate(ctx context.Context, arg ListLiveSlotsForUpdateParams) ([]ListLiveSlotsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listLiveSlotsForUpdate, arg.LabsID, arg.ResourcePoolsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveSlotsForUpdateRow{}
	for rows.Next() {
		var i ListLiveSlotsForUpdateRow
		if err := rows.Scan(
			&i.SlotsID,
			&i.LabsID,
			&i.UsersID,
			&i.ResourcePoolsID,
			&i.ResourcesID,
			&i.SlotPriority,
			&i.Status,
			&i.DesiredStart,
			&i.Lookahead,
			&i.Duration,
			&i.CommittedStart,
			&i.ActualStart,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
SELECT resources_id, resource_pools_id, labs_id, kind, name
FROM resources
WHERE labs_id = $1 AND resource_pools_id = $2
ORDER BY resources_id
`

type ListResourcesParams struct {
	LabsID          uuid.UUID
	ResourcePoolsID uuid.UUID
}

type ListResourcesRow struct {
	ResourcesID     uuid.UUID
	ResourcePoolsID uuid.UUID
	LabsID          uuid.UUID
	Kind            string
	Name            string
}

func (q *Queries) ListResources(ctx context.Context, arg ListResourcesParams) ([]ListResourcesRow, error) {
	rows, err := q.db.Query(ctx, listResources, arg.LabsID, arg.ResourcePoolsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourcesRow{}
	for rows.Next() {
		var i ListResourcesRow
		if err := rows.Scan(
			&i.ResourcesID,
			&i.ResourcePoolsID,
			&i.LabsID,
			&i.Kind,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlots = `-- name: ListSlots :many
SELECT slots_id, labs_id, users_id, resource_pools_id, resources_id,
       slot_priority, status, desired_start, lookahead, duration,
       committed_start, actual_start, note
FROM slots
WHERE labs_id = $1 AND resource_pools_id = $2
ORDER BY desired_start, slots_id
`

type ListSlotsParams struct {
	LabsID          uuid.UUID
	ResourcePoolsID uuid.UUID
}

type ListSlotsRow struct {
	SlotsID         uuid.UUID
	LabsID          uuid.UUID
	UsersID         uuid.UUID
	ResourcePoolsID uuid.UUID
	ResourcesID     *uuid.UUID
	SlotPriority    int64
	Status          string
	DesiredStart    time.Time
	Lookahead       int32
	Duration        int32
	CommittedStart  *time.Time
	ActualStart     *time.Time
	Note            string
}

func (q *Queries) ListSlots(ctx context.Context, arg ListSlotsParams) ([]ListSlotsRow, error) {
	rows, err := q.db.Query(ctx, listSlots, arg.LabsID, arg.ResourcePoolsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSlotsRow{}
	for rows.Next() {
		var i ListSlotsRow
		if err := rows.Scan(
			&i.SlotsID,
			&i.LabsID,
			&i.UsersID,
			&i.ResourcePoolsID,
			&i.ResourcesID,
			&i.SlotPriority,
			&i.Status,
			&i.DesiredStart,
			&i.Lookahead,
			&i.Duration,
			&i.CommittedStart,
			&i.ActualStart,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resourcePoolByID = `-- name: ResourcePoolByID :one
SELECT resource_pools_id, labs_id, kind, name
FROM resource_pools
WHERE labs_id = $1 AND resource_pools_id = $2
`

type ResourcePoolByIDParams struct {
	LabsID          uuid.UUID
	ResourcePoolsID uuid.UUID
}

type ResourcePoolByIDRow struct {
	ResourcePoolsID uuid.UUID
	LabsID          uuid.UUID
	Kind            string
	Name            string
}

func (q *Queries) ResourcePoolByID(ctx context.Context, arg ResourcePoolByIDParams) (ResourcePoolByIDRow, error) {
	row := q.db.QueryRow(ctx, resourcePoolByID, arg.LabsID, arg.ResourcePoolsID)
	var i ResourcePoolByIDRow
	err := row.Scan(
		&i.ResourcePoolsID,
		&i.LabsID,
		&i.Kind,
		&i.Name,
	)
	return i, err
}

const slotByID = `-- name: SlotByID :one
SELECT slots_id, labs_id, users_id, resource_pools_id, resources_id,
       slot_priority, status, desired_start, lookahead, duration,
       committed_start, actual_start, note
FROM slots
WHERE labs_id = $1 AND slots_id = $2
`

type SlotByIDParams struct {
	LabsID  uuid.UUID
	SlotsID uuid.UUID
}

type SlotByIDRow struct {
	SlotsID         uuid.UUID
	LabsID          uuid.UUID
	UsersID         uuid.UUID
	ResourcePoolsID uuid.UUID
	ResourcesID     *uuid.UUID
	SlotPriority    int64
	Status          string
	DesiredStart    time.Time
	Lookahead       int32
	Duration        int32
	CommittedStart  *time.Time
	ActualStart     *time.Time
	Note            string
}

func (q *Queries) SlotByID(ctx context.Context, arg SlotByIDParams) (SlotByIDRow, error) {
	row := q.db.QueryRow(ctx, slotByID, arg.LabsID, arg.SlotsID)
	var i SlotByIDRow
	err := row.Scan(
		&i.SlotsID,
		&i.LabsID,
		&i.UsersID,
		&i.ResourcePoolsID,
		&i.ResourcesID,
		&i.SlotPriority,
		&i.Status,
		&i.DesiredStart,
		&i.Lookahead,
		&i.Duration,
		&i.CommittedStart,
		&i.ActualStart,
		&i.Note,
	)
	return i, err
}

const upsertSlot = `-- name: UpsertSlot :exec
INSERT INTO slots (
    slots_id, labs_id, users_id, resource_pools_id, resources_id,
    slot_priority, desired_start, lookahead, duration,
    committed_start, actual_start, status, note, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12::slot_status, $13, $14, $14
)
ON CONFLICT (slots_id) DO UPDATE SET
    resources_id      = EXCLUDED.resources_id,
    resource_pools_id = EXCLUDED.resource_pools_id,
    slot_priority     = EXCLUDED.slot_priority,
    desired_start     = EXCLUDED.desired_start,
    lookahead         = EXCLUDED.lookahead,
    duration          = EXCLUDED.duration,
    committed_start   = EXCLUDED.committed_start,
    actual_start      = EXCLUDED.actual_start,
    status            = EXCLUDED.status,
    note              = EXCLUDED.note,
    updated_by        = EXCLUDED.updated_by
`

type UpsertSlotParams struct {
	SlotsID         uuid.UUID
	LabsID          uuid.UUID
	UsersID         uuid.UUID
	ResourcePoolsID uuid.UUID
	ResourcesID     *uuid.UUID
	SlotPriority    int64
	DesiredStart    time.Time
	Lookahead       int32
	Duration        int32
	CommittedStart  *time.Time
	ActualStart     *time.Time
	Status          string
	Note            string
	Actor           *uuid.UUID
}

func (q *Queries) UpsertSlot(ctx context.Context, arg UpsertSlotParams) error {
	_, err := q.db.Exec(ctx, upsertSlot,
		arg.SlotsID,
		arg.LabsID,
		arg.UsersID,
		arg.ResourcePoolsID,
		arg.ResourcesID,
		arg.SlotPriority,
		arg.DesiredStart,
		arg.Lookahead,
		arg.Duration,
		arg.CommittedStart,
		arg.ActualStart,
		arg.Status,
		arg.Note,
		arg.Actor,
	)
	return err
}
