// Code generated by "enumer -type=Outcome -trimprefix=Outcome -transform=snake-upper -output=outcome_enumer.go"; DO NOT EDIT.

package dynamicqueue

import (
	"fmt"
	"strings"
)

const _OutcomeName = "UNKNOWNPLACEDNO_SHOW"

var _OutcomeIndex = [...]uint8{0, 7, 13, 20}

const _OutcomeLowerName = "unknownplacedno_show"

func (i Outcome) String() string {
	if i < 0 || i >= Outcome(len(_OutcomeIndex)-1) {
		return fmt.Sprintf("Outcome(%d)", i)
	}
	return _OutcomeName[_OutcomeIndex[i]:_OutcomeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _OutcomeNoOp() {
	var x [1]struct{}
	_ = x[OutcomeUnknown-(0)]
	_ = x[OutcomePlaced-(1)]
	_ = x[OutcomeNoShow-(2)]
}

var _OutcomeValues = []Outcome{OutcomeUnknown, OutcomePlaced, OutcomeNoShow}

var _OutcomeNameToValueMap = map[string]Outcome{
	_OutcomeName[0:7]:        OutcomeUnknown,
	_OutcomeLowerName[0:7]:   OutcomeUnknown,
	_OutcomeName[7:13]:       OutcomePlaced,
	_OutcomeLowerName[7:13]:  OutcomePlaced,
	_OutcomeName[13:20]:      OutcomeNoShow,
	_OutcomeLowerName[13:20]: OutcomeNoShow,
}

var _OutcomeNames = []string{
	_OutcomeName[0:7],
	_OutcomeName[7:13],
	_OutcomeName[13:20],
}

// OutcomeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func OutcomeString(s string) (Outcome, error) {
	if val, ok := _OutcomeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _OutcomeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Outcome values", s)
}

// OutcomeValues returns all values of the enum
func OutcomeValues() []Outcome {
	return _OutcomeValues
}

// OutcomeStrings returns a slice of all String values of the enum
func OutcomeStrings() []string {
	strs := make([]string, len(_OutcomeNames))
	copy(strs, _OutcomeNames)
	return strs
}

// IsAOutcome returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Outcome) IsAOutcome() bool {
	for _, v := range _OutcomeValues {
		if i == v {
			return true
		}
	}
	return false
}
