// Code generated by "enumer -type=SlotStatus -trimprefix=SlotStatus -transform=snake-upper -output=slotstatus_enumer.go"; DO NOT EDIT.

package dynamicqueue

import (
	"fmt"
	"strings"
)

const _SlotStatusName = "UNKNOWNSCHEDULEDACTIVE"

var _SlotStatusIndex = [...]uint8{0, 7, 16, 22}

const _SlotStatusLowerName = "unknownscheduledactive"

func (i SlotStatus) String() string {
	if i < 0 || i >= SlotStatus(len(_SlotStatusIndex)-1) {
		return fmt.Sprintf("SlotStatus(%d)", i)
	}
	return _SlotStatusName[_SlotStatusIndex[i]:_SlotStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SlotStatusNoOp() {
	var x [1]struct{}
	_ = x[SlotStatusUnknown-(0)]
	_ = x[SlotStatusScheduled-(1)]
	_ = x[SlotStatusActive-(2)]
}

var _SlotStatusValues = []SlotStatus{SlotStatusUnknown, SlotStatusScheduled, SlotStatusActive}

var _SlotStatusNameToValueMap = map[string]SlotStatus{
	_SlotStatusName[0:7]:        SlotStatusUnknown,
	_SlotStatusLowerName[0:7]:   SlotStatusUnknown,
	_SlotStatusName[7:16]:       SlotStatusScheduled,
	_SlotStatusLowerName[7:16]:  SlotStatusScheduled,
	_SlotStatusName[16:22]:      SlotStatusActive,
	_SlotStatusLowerName[16:22]: SlotStatusActive,
}

var _SlotStatusNames = []string{
	_SlotStatusName[0:7],
	_SlotStatusName[7:16],
	_SlotStatusName[16:22],
}

// SlotStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SlotStatusString(s string) (SlotStatus, error) {
	if val, ok := _SlotStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SlotStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SlotStatus values", s)
}

// SlotStatusValues returns all values of the enum
func SlotStatusValues() []SlotStatus {
	return _SlotStatusValues
}

// SlotStatusStrings returns a slice of all String values of the enum
func SlotStatusStrings() []string {
	strs := make([]string, len(_SlotStatusNames))
	copy(strs, _SlotStatusNames)
	return strs
}

// IsASlotStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SlotStatus) IsASlotStatus() bool {
	for _, v := range _SlotStatusValues {
		if i == v {
			return true
		}
	}
	return false
}
