// Code generated by "enumer -type=StepKind -trimprefix=StepKind -transform=snake-upper -output=stepkind_enumer.go"; DO NOT EDIT.

package dynamicqueue

import (
	"fmt"
	"strings"
)

const _StepKindName = "UNKNOWNSEED_RESOURCENO_SHOWPLACEGAP_FILLRECOMMIT"

var _StepKindIndex = [...]uint8{0, 7, 20, 27, 32, 40, 48}

const _StepKindLowerName = "unknownseed_resourceno_showplacegap_fillrecommit"

func (i StepKind) String() string {
	if i < 0 || i >= StepKind(len(_StepKindIndex)-1) {
		return fmt.Sprintf("StepKind(%d)", i)
	}
	return _StepKindName[_StepKindIndex[i]:_StepKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StepKindNoOp() {
	var x [1]struct{}
	_ = x[StepKindUnknown-(0)]
	_ = x[StepKindSeedResource-(1)]
	_ = x[StepKindNoShow-(2)]
	_ = x[StepKindPlace-(3)]
	_ = x[StepKindGapFill-(4)]
	_ = x[StepKindRecommit-(5)]
}

var _StepKindValues = []StepKind{StepKindUnknown, StepKindSeedResource, StepKindNoShow, StepKindPlace, StepKindGapFill, StepKindRecommit}

var _StepKindNameToValueMap = map[string]StepKind{
	_StepKindName[0:7]:        StepKindUnknown,
	_StepKindLowerName[0:7]:   StepKindUnknown,
	_StepKindName[7:20]:       StepKindSeedResource,
	_StepKindLowerName[7:20]:  StepKindSeedResource,
	_StepKindName[20:27]:      StepKindNoShow,
	_StepKindLowerName[20:27]: StepKindNoShow,
	_StepKindName[27:32]:      StepKindPlace,
	_StepKindLowerName[27:32]: StepKindPlace,
	_StepKindName[32:40]:      StepKindGapFill,
	_StepKindLowerName[32:40]: StepKindGapFill,
	_StepKindName[40:48]:      StepKindRecommit,
	_StepKindLowerName[40:48]: StepKindRecommit,
}

var _StepKindNames = []string{
	_StepKindName[0:7],
	_StepKindName[7:20],
	_StepKindName[20:27],
	_StepKindName[27:32],
	_StepKindName[32:40],
	_StepKindName[40:48],
}

// StepKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StepKindString(s string) (StepKind, error) {
	if val, ok := _StepKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StepKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to StepKind values", s)
}

// StepKindValues returns all values of the enum
func StepKindValues() []StepKind {
	return _StepKindValues
}

// StepKindStrings returns a slice of all String values of the enum
func StepKindStrings() []string {
	strs := make([]string, len(_StepKindNames))
	copy(strs, _StepKindNames)
	return strs
}

// IsAStepKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i StepKind) IsAStepKind() bool {
	for _, v := range _StepKindValues {
		if i == v {
			return true
		}
	}
	return false
}
