// Code generated by "enumer -type=SlotStatus -trimprefix=SlotStatus -transform=snake-upper -output=slotstatus_enumer.go"; DO NOT EDIT.

package scheduling

import (
	"fmt"
	"strings"
)

const _SlotStatusName = "UNKNOWNSCHEDULEDACTIVECOMPLETECANCELLEDNO_SHOW"

var _SlotStatusIndex = [...]uint8{0, 7, 16, 22, 30, 39, 46}

const _SlotStatusLowerName = "unknownscheduledactivecompletecancelledno_show"

func (i SlotStatus) String() string {
	if i < 0 || i >= SlotStatus(len(_SlotStatusIndex)-1) {
		return fmt.Sprintf("SlotStatus(%d)", i)
	}
	return _SlotStatusName[_SlotStatusIndex[i]:_SlotStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SlotStatusNoOp() {
	var x [1]struct{}
	_ = x[SlotStatusUnknown-(0)]
	_ = x[SlotStatusScheduled-(1)]
	_ = x[SlotStatusActive-(2)]
	_ = x[SlotStatusComplete-(3)]
	_ = x[SlotStatusCancelled-(4)]
	_ = x[SlotStatusNoShow-(5)]
}

var _SlotStatusValues = []SlotStatus{SlotStatusUnknown, SlotStatusScheduled, SlotStatusActive, SlotStatusComplete, SlotStatusCancelled, SlotStatusNoShow}

var _SlotStatusNameToValueMap = map[string]SlotStatus{
	_SlotStatusName[0:7]:        SlotStatusUnknown,
	_SlotStatusLowerName[0:7]:   SlotStatusUnknown,
	_SlotStatusName[7:16]:       SlotStatusScheduled,
	_SlotStatusLowerName[7:16]:  SlotStatusScheduled,
	_SlotStatusName[16:22]:      SlotStatusActive,
	_SlotStatusLowerName[16:22]: SlotStatusActive,
	_SlotStatusName[22:30]:      SlotStatusComplete,
	_SlotStatusLowerName[22:30]: SlotStatusComplete,
	_SlotStatusName[30:39]:      SlotStatusCancelled,
	_SlotStatusLowerName[30:39]: SlotStatusCancelled,
	_SlotStatusName[39:46]:      SlotStatusNoShow,
	_SlotStatusLowerName[39:46]: SlotStatusNoShow,
}

var _SlotStatusNames = []string{
	_SlotStatusName[0:7],
	_SlotStatusName[7:16],
	_SlotStatusName[16:22],
	_SlotStatusName[22:30],
	_SlotStatusName[30:39],
	_SlotStatusName[39:46],
}

// SlotStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SlotStatusString(s string) (SlotStatus, error) {
	if val, ok := _SlotStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SlotStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SlotStatus values", s)
}

// SlotStatusValues returns all values of the enum
func SlotStatusValues() []SlotStatus {
	return _SlotStatusValues
}

// SlotStatusStrings returns a slice of all String values of the enum
func SlotStatusStrings() []string {
	strs := make([]string, len(_SlotStatusNames))
	copy(strs, _SlotStatusNames)
	return strs
}

// IsASlotStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SlotStatus) IsASlotStatus() bool {
	for _, v := range _SlotStatusValues {
		if i == v {
			return true
		}
	}
	return false
}
